import 'class_schedule.dart';
import 'map_schedule_entries.dart';

List<Schedule> mondayList = [
  Schedule(
      hour: 13,
      minute: 41,
      lunch1: scheduleEntries["H-1424-Fin"]!,
      lunch2: scheduleEntries["H-1424-Fin"]!,
      lunch3: scheduleEntries["H-1424-Fin"]!),
  Schedule(
      hour: 13,
      minute: 38,
      lunch1: scheduleEntries["Pass-1341-H"]!,
      lunch2: scheduleEntries["Pass-1341-H"]!,
      lunch3: scheduleEntries["Pass-1341-H"]!),
  Schedule(
      hour: 12,
      minute: 56,
      lunch1: scheduleEntries["G-1338-H"]!,
      lunch2: scheduleEntries["G-1338-H"]!,
      lunch3: scheduleEntries["G-1338-H"]!),
  Schedule(
      hour: 12,
      minute: 53,
      lunch1: scheduleEntries["Pass-1256-G"]!,
      lunch2: scheduleEntries["Pass-1256-G"]!,
      lunch3: scheduleEntries["Pass-1256-G"]!),
  Schedule(
      hour: 12,
      minute: 23,
      lunch1: scheduleEntries["F-1253-G"]!,
      lunch2: scheduleEntries["F-1253-G"]!,
      lunch3: scheduleEntries["L-1253-G"]!),
  Schedule(
      hour: 12,
      minute: 20,
      lunch1: scheduleEntries["F-1253-G"]!,
      lunch2: scheduleEntries["F-1253-G"]!,
      lunch3: scheduleEntries["Pass-1223-L"]!),
  Schedule(
      hour: 12,
      minute: 10,
      lunch1: scheduleEntries["F-1253-G"]!,
      lunch2: scheduleEntries["F-1253-G"]!,
      lunch3: scheduleEntries["F-1220-L"]!),
  Schedule(
      hour: 12,
      minute: 7,
      lunch1: scheduleEntries["Pass-1210-F"]!,
      lunch2: scheduleEntries["Pass-1210-F"]!,
      lunch3: scheduleEntries["F-1220-L"]!),
  Schedule(
      hour: 11,
      minute: 37,
      lunch1: scheduleEntries["E-1207-F"]!,
      lunch2: scheduleEntries["L-1207-F"]!,
      lunch3: scheduleEntries["F-1220-L"]!),
  Schedule(
      hour: 11,
      minute: 34,
      lunch1: scheduleEntries["E-1207-F"]!,
      lunch2: scheduleEntries["Pass-1137-L"]!,
      lunch3: scheduleEntries["Pass-1137-F"]!),
  Schedule(
      hour: 11,
      minute: 24,
      lunch1: scheduleEntries["E-1207-F"]!,
      lunch2: scheduleEntries["E-1134-L"]!,
      lunch3: scheduleEntries["E-1134-F"]!),
  Schedule(
      hour: 11,
      minute: 21,
      lunch1: scheduleEntries["Pass-1124-E"]!,
      lunch2: scheduleEntries["E-1134-L"]!,
      lunch3: scheduleEntries["E-1134-F"]!),
  Schedule(
      hour: 10,
      minute: 51,
      lunch1: scheduleEntries["L-1121-E"]!,
      lunch2: scheduleEntries["E-1134-L"]!,
      lunch3: scheduleEntries["E-1134-F"]!),
  Schedule(
      hour: 10,
      minute: 48,
      lunch1: scheduleEntries["Pass-1051-L"]!,
      lunch2: scheduleEntries["Pass-1051-E"]!,
      lunch3: scheduleEntries["Pass-1051-E"]!),
  Schedule(
      hour: 10,
      minute: 5,
      lunch1: scheduleEntries["D-1048-L"]!,
      lunch2: scheduleEntries["D-1048-E"]!,
      lunch3: scheduleEntries["D-1048-E"]!),
  Schedule(
      hour: 10,
      minute: 2,
      lunch1: scheduleEntries["Pass-1005-D"]!,
      lunch2: scheduleEntries["Pass-1005-D"]!,
      lunch3: scheduleEntries["Pass-1005-D"]!),
  Schedule(
      hour: 9,
      minute: 19,
      lunch1: scheduleEntries["C-1002-D"]!,
      lunch2: scheduleEntries["C-1002-D"]!,
      lunch3: scheduleEntries["C-1002-D"]!),
  Schedule(
      hour: 9,
      minute: 16,
      lunch1: scheduleEntries["Pass-919-C"]!,
      lunch2: scheduleEntries["Pass-919-C"]!,
      lunch3: scheduleEntries["Pass-919-C"]!),
  Schedule(
      hour: 8,
      minute: 33,
      lunch1: scheduleEntries["B-916-C"]!,
      lunch2: scheduleEntries["B-916-C"]!,
      lunch3: scheduleEntries["B-916-C"]!),
  Schedule(
      hour: 8,
      minute: 30,
      lunch1: scheduleEntries["Pass-833-B"]!,
      lunch2: scheduleEntries["Pass-833-B"]!,
      lunch3: scheduleEntries["Pass-833-B"]!),
  Schedule(
      hour: 7,
      minute: 45,
      lunch1: scheduleEntries["A-830-B"]!,
      lunch2: scheduleEntries["A-830-B"]!,
      lunch3: scheduleEntries["A-830-B"]!),
  Schedule(
      hour: 7,
      minute: 43,
      lunch1: scheduleEntries["Second-745-A"]!,
      lunch2: scheduleEntries["Second-745-A"]!,
      lunch3: scheduleEntries["Second-745-A"]!),
  Schedule(
      hour: 7,
      minute: 40,
      lunch1: scheduleEntries["Pass-745-A"]!,
      lunch2: scheduleEntries["Pass-745-A"]!,
      lunch3: scheduleEntries["Pass-745-A"]!),
  Schedule(
      hour: 7,
      minute: 35,
      lunch1: scheduleEntries["First-745-A"]!,
      lunch2: scheduleEntries["First-745-A"]!,
      lunch3: scheduleEntries["First-745-A"]!),
  Schedule(
      hour: 6,
      minute: 45,
      lunch1: scheduleEntries["Open-745-A"]!,
      lunch2: scheduleEntries["Open-745-A"]!,
      lunch3: scheduleEntries["Open-745-A"]!),
];

List<Schedule> tuesdayList = [
  Schedule(
      hour: 13,
      minute: 26,
      lunch1: scheduleEntries["H-1424-Fin"]!,
      lunch2: scheduleEntries["H-1424-Fin"]!,
      lunch3: scheduleEntries["H-1424-Fin"]!),
  Schedule(
      hour: 13,
      minute: 22,
      lunch1: scheduleEntries["Pass-1326-H"]!,
      lunch2: scheduleEntries["Pass-1326-H"]!,
      lunch3: scheduleEntries["Pass-1326-H"]!),
  Schedule(
      hour: 12,
      minute: 52,
      lunch1: scheduleEntries["F-1322-H"]!,
      lunch2: scheduleEntries["F-1322-H"]!,
      lunch3: scheduleEntries["L-1322-H"]!),
  Schedule(
      hour: 12,
      minute: 49,
      lunch1: scheduleEntries["F-1322-H"]!,
      lunch2: scheduleEntries["F-1322-H"]!,
      lunch3: scheduleEntries["Pass-1252-L"]!),
  Schedule(
      hour: 12,
      minute: 24,
      lunch1: scheduleEntries["F-1322-H"]!,
      lunch2: scheduleEntries["F-1322-H"]!,
      lunch3: scheduleEntries["F-1249-L"]!),
  Schedule(
      hour: 12,
      minute: 21,
      lunch1: scheduleEntries["Pass-1224-F"]!,
      lunch2: scheduleEntries["Pass-1224-F"]!,
      lunch3: scheduleEntries["F-1249-L"]!),
  Schedule(
      hour: 11,
      minute: 51,
      lunch1: scheduleEntries["E-1221-F"]!,
      lunch2: scheduleEntries["L-1221-F"]!,
      lunch3: scheduleEntries["F-1249-L"]!),
  Schedule(
      hour: 11,
      minute: 48,
      lunch1: scheduleEntries["E-1221-F"]!,
      lunch2: scheduleEntries["Pass-1151-L"]!,
      lunch3: scheduleEntries["Pass-1151-F"]!),
  Schedule(
      hour: 11,
      minute: 23,
      lunch1: scheduleEntries["E-1221-F"]!,
      lunch2: scheduleEntries["E-1148-L"]!,
      lunch3: scheduleEntries["E-1148-F"]!),
  Schedule(
      hour: 11,
      minute: 20,
      lunch1: scheduleEntries["Pass-1123-E"]!,
      lunch2: scheduleEntries["E-1148-L"]!,
      lunch3: scheduleEntries["E-1148-F"]!),
  Schedule(
      hour: 10,
      minute: 50,
      lunch1: scheduleEntries["L-1120-E"]!,
      lunch2: scheduleEntries["E-1148-L"]!,
      lunch3: scheduleEntries["E-1148-F"]!),
  Schedule(
      hour: 10,
      minute: 47,
      lunch1: scheduleEntries["Pass-1050-L"]!,
      lunch2: scheduleEntries["Pass-1050-E"]!,
      lunch3: scheduleEntries["Pass-1050-E"]!),
  Schedule(
      hour: 9,
      minute: 49,
      lunch1: scheduleEntries["D-1047-L"]!,
      lunch2: scheduleEntries["D-1047-E"]!,
      lunch3: scheduleEntries["D-1047-E"]!),
  Schedule(
      hour: 9,
      minute: 46,
      lunch1: scheduleEntries["Pass-949-D"]!,
      lunch2: scheduleEntries["Pass-949-D"]!,
      lunch3: scheduleEntries["Pass-949-D"]!),
  Schedule(
      hour: 8,
      minute: 48,
      lunch1: scheduleEntries["B-946-D"]!,
      lunch2: scheduleEntries["B-946-D"]!,
      lunch3: scheduleEntries["B-946-D"]!),
  Schedule(
      hour: 8,
      minute: 45,
      lunch1: scheduleEntries["Pass-848-B"]!,
      lunch2: scheduleEntries["Pass-848-B"]!,
      lunch3: scheduleEntries["Pass-848-B"]!),
  Schedule(
      hour: 7,
      minute: 45,
      lunch1: scheduleEntries["A-845-B"]!,
      lunch2: scheduleEntries["A-845-B"]!,
      lunch3: scheduleEntries["A-845-B"]!),
  Schedule(
      hour: 7,
      minute: 43,
      lunch1: scheduleEntries["Second-745-A"]!,
      lunch2: scheduleEntries["Second-745-A"]!,
      lunch3: scheduleEntries["Second-745-A"]!),
  Schedule(
      hour: 7,
      minute: 40,
      lunch1: scheduleEntries["Pass-745-A"]!,
      lunch2: scheduleEntries["Pass-745-A"]!,
      lunch3: scheduleEntries["Pass-745-A"]!),
  Schedule(
      hour: 7,
      minute: 35,
      lunch1: scheduleEntries["First-745-A"]!,
      lunch2: scheduleEntries["First-745-A"]!,
      lunch3: scheduleEntries["First-745-A"]!),
  Schedule(
      hour: 6,
      minute: 45,
      lunch1: scheduleEntries["Open-745-A"]!,
      lunch2: scheduleEntries["Open-745-A"]!,
      lunch3: scheduleEntries["Open-745-A"]!),
];

List<Schedule> wednesdayList = [
  Schedule(
      hour: 13,
      minute: 26,
      lunch1: scheduleEntries["H-1424-Fin"]!,
      lunch2: scheduleEntries["H-1424-Fin"]!,
      lunch3: scheduleEntries["H-1424-Fin"]!),
  Schedule(
      hour: 13,
      minute: 22,
      lunch1: scheduleEntries["Pass-1326-H"]!,
      lunch2: scheduleEntries["Pass-1326-H"]!,
      lunch3: scheduleEntries["Pass-1326-H"]!),
  Schedule(
      hour: 12,
      minute: 52,
      lunch1: scheduleEntries["G-1322-H"]!,
      lunch2: scheduleEntries["G-1322-H"]!,
      lunch3: scheduleEntries["L-1322-H"]!),
  Schedule(
      hour: 12,
      minute: 49,
      lunch1: scheduleEntries["G-1322-H"]!,
      lunch2: scheduleEntries["G-1322-H"]!,
      lunch3: scheduleEntries["Pass-1252-L"]!),
  Schedule(
      hour: 12,
      minute: 24,
      lunch1: scheduleEntries["G-1322-H"]!,
      lunch2: scheduleEntries["G-1322-H"]!,
      lunch3: scheduleEntries["G-1249-L"]!),
  Schedule(
      hour: 12,
      minute: 21,
      lunch1: scheduleEntries["Pass-1224-G"]!,
      lunch2: scheduleEntries["Pass-1224-G"]!,
      lunch3: scheduleEntries["G-1249-L"]!),
  Schedule(
      hour: 11,
      minute: 51,
      lunch1: scheduleEntries["E-1221-G"]!,
      lunch2: scheduleEntries["L-1221-G"]!,
      lunch3: scheduleEntries["G-1249-L"]!),
  Schedule(
      hour: 11,
      minute: 48,
      lunch1: scheduleEntries["E-1221-G"]!,
      lunch2: scheduleEntries["Pass-1151-L"]!,
      lunch3: scheduleEntries["Pass-1151-G"]!),
  Schedule(
      hour: 11,
      minute: 23,
      lunch1: scheduleEntries["E-1221-G"]!,
      lunch2: scheduleEntries["E-1148-L"]!,
      lunch3: scheduleEntries["E-1148-G"]!),
  Schedule(
      hour: 11,
      minute: 20,
      lunch1: scheduleEntries["Pass-1123-E"]!,
      lunch2: scheduleEntries["E-1148-L"]!,
      lunch3: scheduleEntries["E-1148-G"]!),
  Schedule(
      hour: 10,
      minute: 50,
      lunch1: scheduleEntries["L-1120-E"]!,
      lunch2: scheduleEntries["E-1148-L"]!,
      lunch3: scheduleEntries["E-1148-G"]!),
  Schedule(
      hour: 10,
      minute: 47,
      lunch1: scheduleEntries["Pass-1050-L"]!,
      lunch2: scheduleEntries["Pass-1050-E"]!,
      lunch3: scheduleEntries["Pass-1050-E"]!),
  Schedule(
      hour: 9,
      minute: 49,
      lunch1: scheduleEntries["D-1047-L"]!,
      lunch2: scheduleEntries["D-1047-E"]!,
      lunch3: scheduleEntries["D-1047-E"]!),
  Schedule(
      hour: 9,
      minute: 46,
      lunch1: scheduleEntries["Pass-949-D"]!,
      lunch2: scheduleEntries["Pass-949-D"]!,
      lunch3: scheduleEntries["Pass-949-D"]!),
  Schedule(
      hour: 8,
      minute: 48,
      lunch1: scheduleEntries["C-946-D"]!,
      lunch2: scheduleEntries["C-946-D"]!,
      lunch3: scheduleEntries["C-946-D"]!),
  Schedule(
      hour: 8,
      minute: 45,
      lunch1: scheduleEntries["Pass-848-C"]!,
      lunch2: scheduleEntries["Pass-848-C"]!,
      lunch3: scheduleEntries["Pass-848-C"]!),
  Schedule(
      hour: 7,
      minute: 45,
      lunch1: scheduleEntries["A-845-C"]!,
      lunch2: scheduleEntries["A-845-C"]!,
      lunch3: scheduleEntries["A-845-C"]!),
  Schedule(
      hour: 7,
      minute: 43,
      lunch1: scheduleEntries["Second-745-A"]!,
      lunch2: scheduleEntries["Second-745-A"]!,
      lunch3: scheduleEntries["Second-745-A"]!),
  Schedule(
      hour: 7,
      minute: 40,
      lunch1: scheduleEntries["Pass-745-A"]!,
      lunch2: scheduleEntries["Pass-745-A"]!,
      lunch3: scheduleEntries["Pass-745-A"]!),
  Schedule(
      hour: 7,
      minute: 35,
      lunch1: scheduleEntries["First-745-A"]!,
      lunch2: scheduleEntries["First-745-A"]!,
      lunch3: scheduleEntries["First-745-A"]!),
  Schedule(
      hour: 6,
      minute: 45,
      lunch1: scheduleEntries["Open-745-A"]!,
      lunch2: scheduleEntries["Open-745-A"]!,
      lunch3: scheduleEntries["Open-745-A"]!),
];

List<Schedule> thursdayList = [
  Schedule(
      hour: 13,
      minute: 26,
      lunch1: scheduleEntries["G-1424-Fin"]!,
      lunch2: scheduleEntries["G-1424-Fin"]!,
      lunch3: scheduleEntries["G-1424-Fin"]!),
  Schedule(
      hour: 13,
      minute: 22,
      lunch1: scheduleEntries["Pass-1326-G"]!,
      lunch2: scheduleEntries["Pass-1326-G"]!,
      lunch3: scheduleEntries["Pass-1326-G"]!),
  Schedule(
      hour: 12,
      minute: 52,
      lunch1: scheduleEntries["F-1322-G"]!,
      lunch2: scheduleEntries["F-1322-G"]!,
      lunch3: scheduleEntries["L-1322-G"]!),
  Schedule(
      hour: 12,
      minute: 49,
      lunch1: scheduleEntries["F-1322-G"]!,
      lunch2: scheduleEntries["F-1322-G"]!,
      lunch3: scheduleEntries["Pass-1252-L"]!),
  Schedule(
      hour: 12,
      minute: 24,
      lunch1: scheduleEntries["F-1322-G"]!,
      lunch2: scheduleEntries["F-1322-G"]!,
      lunch3: scheduleEntries["F-1249-L"]!),
  Schedule(
      hour: 12,
      minute: 21,
      lunch1: scheduleEntries["Pass-1224-F"]!,
      lunch2: scheduleEntries["Pass-1224-F"]!,
      lunch3: scheduleEntries["F-1249-L"]!),
  Schedule(
      hour: 11,
      minute: 51,
      lunch1: scheduleEntries["E-1221-F"]!,
      lunch2: scheduleEntries["L-1221-F"]!,
      lunch3: scheduleEntries["F-1249-L"]!),
  Schedule(
      hour: 11,
      minute: 48,
      lunch1: scheduleEntries["E-1221-F"]!,
      lunch2: scheduleEntries["Pass-1151-L"]!,
      lunch3: scheduleEntries["Pass-1151-F"]!),
  Schedule(
      hour: 11,
      minute: 23,
      lunch1: scheduleEntries["E-1221-F"]!,
      lunch2: scheduleEntries["E-1148-L"]!,
      lunch3: scheduleEntries["E-1148-F"]!),
  Schedule(
      hour: 11,
      minute: 20,
      lunch1: scheduleEntries["Pass-1123-E"]!,
      lunch2: scheduleEntries["E-1148-L"]!,
      lunch3: scheduleEntries["E-1148-F"]!),
  Schedule(
      hour: 10,
      minute: 50,
      lunch1: scheduleEntries["L-1120-E"]!,
      lunch2: scheduleEntries["E-1148-L"]!,
      lunch3: scheduleEntries["E-1148-F"]!),
  Schedule(
      hour: 10,
      minute: 47,
      lunch1: scheduleEntries["Pass-1050-L"]!,
      lunch2: scheduleEntries["Pass-1050-E"]!,
      lunch3: scheduleEntries["Pass-1050-E"]!),
  Schedule(
      hour: 9,
      minute: 49,
      lunch1: scheduleEntries["C-1047-L"]!,
      lunch2: scheduleEntries["C-1047-E"]!,
      lunch3: scheduleEntries["C-1047-E"]!),
  Schedule(
      hour: 9,
      minute: 46,
      lunch1: scheduleEntries["Pass-949-C"]!,
      lunch2: scheduleEntries["Pass-949-C"]!,
      lunch3: scheduleEntries["Pass-949-C"]!),
  Schedule(
      hour: 8,
      minute: 48,
      lunch1: scheduleEntries["B-946-C"]!,
      lunch2: scheduleEntries["B-946-C"]!,
      lunch3: scheduleEntries["B-946-C"]!),
  Schedule(
      hour: 8,
      minute: 45,
      lunch1: scheduleEntries["Pass-848-B"]!,
      lunch2: scheduleEntries["Pass-848-B"]!,
      lunch3: scheduleEntries["Pass-848-B"]!),
  Schedule(
      hour: 7,
      minute: 45,
      lunch1: scheduleEntries["A-845-B"]!,
      lunch2: scheduleEntries["A-845-B"]!,
      lunch3: scheduleEntries["A-845-B"]!),
  Schedule(
      hour: 7,
      minute: 43,
      lunch1: scheduleEntries["Second-745-A"]!,
      lunch2: scheduleEntries["Second-745-A"]!,
      lunch3: scheduleEntries["Second-745-A"]!),
  Schedule(
      hour: 7,
      minute: 40,
      lunch1: scheduleEntries["Pass-745-A"]!,
      lunch2: scheduleEntries["Pass-745-A"]!,
      lunch3: scheduleEntries["Pass-745-A"]!),
  Schedule(
      hour: 7,
      minute: 35,
      lunch1: scheduleEntries["First-745-A"]!,
      lunch2: scheduleEntries["First-745-A"]!,
      lunch3: scheduleEntries["First-745-A"]!),
  Schedule(
      hour: 6,
      minute: 45,
      lunch1: scheduleEntries["Open-745-A"]!,
      lunch2: scheduleEntries["Open-745-A"]!,
      lunch3: scheduleEntries["Open-745-A"]!),
];

List<Schedule> fridayList = [
  Schedule(
      hour: 13,
      minute: 26,
      lunch1: scheduleEntries["H-1424-Fin"]!,
      lunch2: scheduleEntries["H-1424-Fin"]!,
      lunch3: scheduleEntries["H-1424-Fin"]!),
  Schedule(
      hour: 13,
      minute: 22,
      lunch1: scheduleEntries["Pass-1326-H"]!,
      lunch2: scheduleEntries["Pass-1326-H"]!,
      lunch3: scheduleEntries["Pass-1326-H"]!),
  Schedule(
      hour: 12,
      minute: 52,
      lunch1: scheduleEntries["G-1322-H"]!,
      lunch2: scheduleEntries["G-1322-H"]!,
      lunch3: scheduleEntries["L-1322-H"]!),
  Schedule(
      hour: 12,
      minute: 49,
      lunch1: scheduleEntries["G-1322-H"]!,
      lunch2: scheduleEntries["G-1322-H"]!,
      lunch3: scheduleEntries["Pass-1252-L"]!),
  Schedule(
      hour: 12,
      minute: 24,
      lunch1: scheduleEntries["G-1322-H"]!,
      lunch2: scheduleEntries["G-1322-H"]!,
      lunch3: scheduleEntries["G-1249-L"]!),
  Schedule(
      hour: 12,
      minute: 21,
      lunch1: scheduleEntries["Pass-1224-G"]!,
      lunch2: scheduleEntries["Pass-1224-G"]!,
      lunch3: scheduleEntries["G-1249-L"]!),
  Schedule(
      hour: 11,
      minute: 51,
      lunch1: scheduleEntries["F-1221-G"]!,
      lunch2: scheduleEntries["L-1221-G"]!,
      lunch3: scheduleEntries["G-1249-L"]!),
  Schedule(
      hour: 11,
      minute: 48,
      lunch1: scheduleEntries["F-1221-G"]!,
      lunch2: scheduleEntries["Pass-1151-L"]!,
      lunch3: scheduleEntries["Pass-1151-G"]!),
  Schedule(
      hour: 11,
      minute: 23,
      lunch1: scheduleEntries["F-1221-G"]!,
      lunch2: scheduleEntries["F-1148-L"]!,
      lunch3: scheduleEntries["F-1148-G"]!),
  Schedule(
      hour: 11,
      minute: 20,
      lunch1: scheduleEntries["Pass-1123-F"]!,
      lunch2: scheduleEntries["F-1148-L"]!,
      lunch3: scheduleEntries["E-1148-G"]!),
  Schedule(
      hour: 10,
      minute: 50,
      lunch1: scheduleEntries["L-1120-F"]!,
      lunch2: scheduleEntries["F-1148-L"]!,
      lunch3: scheduleEntries["F-1148-G"]!),
  Schedule(
      hour: 10,
      minute: 47,
      lunch1: scheduleEntries["Pass-1050-L"]!,
      lunch2: scheduleEntries["Pass-1050-F"]!,
      lunch3: scheduleEntries["Pass-1050-F"]!),
  Schedule(
      hour: 9,
      minute: 49,
      lunch1: scheduleEntries["D-1047-L"]!,
      lunch2: scheduleEntries["D-1047-F"]!,
      lunch3: scheduleEntries["D-1047-F"]!),
  Schedule(
      hour: 9,
      minute: 46,
      lunch1: scheduleEntries["Pass-949-D"]!,
      lunch2: scheduleEntries["Pass-949-D"]!,
      lunch3: scheduleEntries["Pass-949-D"]!),
  Schedule(
      hour: 8,
      minute: 48,
      lunch1: scheduleEntries["C-946-D"]!,
      lunch2: scheduleEntries["C-946-D"]!,
      lunch3: scheduleEntries["C-946-D"]!),
  Schedule(
      hour: 8,
      minute: 45,
      lunch1: scheduleEntries["Pass-848-C"]!,
      lunch2: scheduleEntries["Pass-848-C"]!,
      lunch3: scheduleEntries["Pass-848-C"]!),
  Schedule(
      hour: 7,
      minute: 45,
      lunch1: scheduleEntries["B-845-C"]!,
      lunch2: scheduleEntries["B-845-C"]!,
      lunch3: scheduleEntries["B-845-C"]!),
  Schedule(
      hour: 7,
      minute: 43,
      lunch1: scheduleEntries["Second-745-B"]!,
      lunch2: scheduleEntries["Second-745-B"]!,
      lunch3: scheduleEntries["Second-745-B"]!),
  Schedule(
      hour: 7,
      minute: 40,
      lunch1: scheduleEntries["Pass-745-B"]!,
      lunch2: scheduleEntries["Pass-745-B"]!,
      lunch3: scheduleEntries["Pass-745-B"]!),
  Schedule(
      hour: 7,
      minute: 35,
      lunch1: scheduleEntries["First-745-B"]!,
      lunch2: scheduleEntries["First-745-B"]!,
      lunch3: scheduleEntries["First-745-B"]!),
  Schedule(
      hour: 6,
      minute: 45,
      lunch1: scheduleEntries["Open-745-B"]!,
      lunch2: scheduleEntries["Open-745-B"]!,
      lunch3: scheduleEntries["Open-745-B"]!),
];
