import 'class_schedule.dart';
import 'map_schedule_entries.dart';

List<Schedule> earlyDismissal241101List = [
  Schedule(
      hour: 10,
      minute: 24,
      lunch1: scheduleEntries["F-1115-Fin"]!,
      lunch2: scheduleEntries["F-1115-Fin"]!,
      lunch3: scheduleEntries["F-1115-Fin"]!),
  Schedule(
      hour: 10,
      minute: 21,
      lunch1: scheduleEntries["Pass-1024-F"]!,
      lunch2: scheduleEntries["Pass-1024-F"]!,
      lunch3: scheduleEntries["Pass-1024-F"]!),
  Schedule(
      hour: 9,
      minute: 31,
      lunch1: scheduleEntries["D-1021-F"]!,
      lunch2: scheduleEntries["D-1021-F"]!,
      lunch3: scheduleEntries["D-1021-F"]!),
  Schedule(
      hour: 9,
      minute: 28,
      lunch1: scheduleEntries["Pass-931-D"]!,
      lunch2: scheduleEntries["Pass-931-D"]!,
      lunch3: scheduleEntries["Pass-931-D"]!),
  Schedule(
      hour: 8,
      minute: 38,
      lunch1: scheduleEntries["C-928-D"]!,
      lunch2: scheduleEntries["C-928-D"]!,
      lunch3: scheduleEntries["C-928-D"]!),
  Schedule(
      hour: 8,
      minute: 35,
      lunch1: scheduleEntries["Pass-838-C"]!,
      lunch2: scheduleEntries["Pass-838-C"]!,
      lunch3: scheduleEntries["Pass-838-C"]!),
  Schedule(
      hour: 7,
      minute: 45,
      lunch1: scheduleEntries["B-835-C"]!,
      lunch2: scheduleEntries["B-835-C"]!,
      lunch3: scheduleEntries["B-835-C"]!),
  Schedule(
      hour: 7,
      minute: 43,
      lunch1: scheduleEntries["Second-745-B"]!,
      lunch2: scheduleEntries["Second-745-B"]!,
      lunch3: scheduleEntries["Second-745-B"]!),
  Schedule(
      hour: 7,
      minute: 40,
      lunch1: scheduleEntries["Pass-745-B"]!,
      lunch2: scheduleEntries["Pass-745-B"]!,
      lunch3: scheduleEntries["Pass-745-B"]!),
  Schedule(
      hour: 7,
      minute: 35,
      lunch1: scheduleEntries["First-745-B"]!,
      lunch2: scheduleEntries["First-745-B"]!,
      lunch3: scheduleEntries["First-745-B"]!),
  Schedule(
      hour: 6,
      minute: 45,
      lunch1: scheduleEntries["Open-745-B"]!,
      lunch2: scheduleEntries["Open-745-B"]!,
      lunch3: scheduleEntries["Open-745-B"]!),
];

List<Schedule> earlyDismissal250418List = [
  Schedule(
      hour: 10,
      minute: 51,
      lunch1: scheduleEntries["H-1115-Fin"]!,
      lunch2: scheduleEntries["H-1115-Fin"]!,
      lunch3: scheduleEntries["H-1115-Fin"]!),
  Schedule(
      hour: 10,
      minute: 48,
      lunch1: scheduleEntries["Pass-1051-H"]!,
      lunch2: scheduleEntries["Pass-1051-H"]!,
      lunch3: scheduleEntries["Pass-1051-H"]!),
  Schedule(
      hour: 10,
      minute: 25,
      lunch1: scheduleEntries["G-1048-H"]!,
      lunch2: scheduleEntries["G-1048-H"]!,
      lunch3: scheduleEntries["G-1048-H"]!),
  Schedule(
      hour: 10,
      minute: 22,
      lunch1: scheduleEntries["Pass-1025-G"]!,
      lunch2: scheduleEntries["Pass-1025-G"]!,
      lunch3: scheduleEntries["Pass-1025-G"]!),
  Schedule(
      hour: 9,
      minute: 58,
      lunch1: scheduleEntries["F-1022-G"]!,
      lunch2: scheduleEntries["F-1022-G"]!,
      lunch3: scheduleEntries["F-1022-G"]!),
  Schedule(
      hour: 9,
      minute: 55,
      lunch1: scheduleEntries["Pass-958-F"]!,
      lunch2: scheduleEntries["Pass-958-F"]!,
      lunch3: scheduleEntries["Pass-958-F"]!),
  Schedule(
      hour: 9,
      minute: 32,
      lunch1: scheduleEntries["E-955-F"]!,
      lunch2: scheduleEntries["E-955-F"]!,
      lunch3: scheduleEntries["E-955-F"]!),
  Schedule(
      hour: 9,
      minute: 29,
      lunch1: scheduleEntries["Pass-932-E"]!,
      lunch2: scheduleEntries["Pass-932-E"]!,
      lunch3: scheduleEntries["Pass-932-E"]!),
  Schedule(
      hour: 9,
      minute: 5,
      lunch1: scheduleEntries["D-929-E"]!,
      lunch2: scheduleEntries["D-929-E"]!,
      lunch3: scheduleEntries["D-929-E"]!),
  Schedule(
      hour: 9,
      minute: 2,
      lunch1: scheduleEntries["Pass-905-D"]!,
      lunch2: scheduleEntries["Pass-905-D"]!,
      lunch3: scheduleEntries["Pass-905-D"]!),
  Schedule(
      hour: 8,
      minute: 39,
      lunch1: scheduleEntries["C-902-D"]!,
      lunch2: scheduleEntries["C-902-D"]!,
      lunch3: scheduleEntries["C-902-D"]!),
  Schedule(
      hour: 8,
      minute: 36,
      lunch1: scheduleEntries["Pass-839-C"]!,
      lunch2: scheduleEntries["Pass-839-C"]!,
      lunch3: scheduleEntries["Pass-839-C"]!),
  Schedule(
      hour: 8,
      minute: 12,
      lunch1: scheduleEntries["B-836-C"]!,
      lunch2: scheduleEntries["B-836-C"]!,
      lunch3: scheduleEntries["B-836-C"]!),
  Schedule(
      hour: 8,
      minute: 9,
      lunch1: scheduleEntries["Pass-812-B"]!,
      lunch2: scheduleEntries["Pass-812-B"]!,
      lunch3: scheduleEntries["Pass-812-B"]!),
  Schedule(
      hour: 7,
      minute: 45,
      lunch1: scheduleEntries["A-809-B"]!,
      lunch2: scheduleEntries["A-809-B"]!,
      lunch3: scheduleEntries["A-809-B"]!),
  Schedule(
      hour: 7,
      minute: 43,
      lunch1: scheduleEntries["Second-745-A"]!,
      lunch2: scheduleEntries["Second-745-B"]!,
      lunch3: scheduleEntries["Second-745-B"]!),
  Schedule(
      hour: 7,
      minute: 40,
      lunch1: scheduleEntries["Pass-745-A"]!,
      lunch2: scheduleEntries["Pass-745-B"]!,
      lunch3: scheduleEntries["Pass-745-B"]!),
  Schedule(
      hour: 7,
      minute: 35,
      lunch1: scheduleEntries["First-745-A"]!,
      lunch2: scheduleEntries["First-745-B"]!,
      lunch3: scheduleEntries["First-745-B"]!),
  Schedule(
      hour: 6,
      minute: 45,
      lunch1: scheduleEntries["Open-745-A"]!,
      lunch2: scheduleEntries["Open-745-B"]!,
      lunch3: scheduleEntries["Open-745-B"]!),
];

List<Schedule> delayedStart241028List = [
  Schedule(
      hour: 13,
      minute: 41,
      lunch1: scheduleEntries["H-1424-Fin"]!,
      lunch2: scheduleEntries["H-1424-Fin"]!,
      lunch3: scheduleEntries["H-1424-Fin"]!),
  Schedule(
      hour: 13,
      minute: 38,
      lunch1: scheduleEntries["Pass-1341-H"]!,
      lunch2: scheduleEntries["Pass-1341-H"]!,
      lunch3: scheduleEntries["Pass-1341-H"]!),
  Schedule(
      hour: 12,
      minute: 56,
      lunch1: scheduleEntries["G-1338-H"]!,
      lunch2: scheduleEntries["G-1338-H"]!,
      lunch3: scheduleEntries["G-1338-H"]!),
  Schedule(
      hour: 12,
      minute: 53,
      lunch1: scheduleEntries["Pass-1256-G"]!,
      lunch2: scheduleEntries["Pass-1256-G"]!,
      lunch3: scheduleEntries["Pass-1256-G"]!),
  Schedule(
      hour: 12,
      minute: 23,
      lunch1: scheduleEntries["F-1253-G"]!,
      lunch2: scheduleEntries["F-1253-G"]!,
      lunch3: scheduleEntries["L-1253-G"]!),
  Schedule(
      hour: 12,
      minute: 20,
      lunch1: scheduleEntries["F-1253-G"]!,
      lunch2: scheduleEntries["F-1253-G"]!,
      lunch3: scheduleEntries["Pass-1223-L"]!),
  Schedule(
      hour: 12,
      minute: 10,
      lunch1: scheduleEntries["F-1253-G"]!,
      lunch2: scheduleEntries["F-1253-G"]!,
      lunch3: scheduleEntries["F-1220-L"]!),
  Schedule(
      hour: 12,
      minute: 7,
      lunch1: scheduleEntries["Pass-1210-F"]!,
      lunch2: scheduleEntries["Pass-1210-F"]!,
      lunch3: scheduleEntries["F-1220-L"]!),
  Schedule(
      hour: 11,
      minute: 37,
      lunch1: scheduleEntries["E-1207-F"]!,
      lunch2: scheduleEntries["L-1207-F"]!,
      lunch3: scheduleEntries["F-1220-L"]!),
  Schedule(
      hour: 11,
      minute: 34,
      lunch1: scheduleEntries["E-1207-F"]!,
      lunch2: scheduleEntries["Pass-1137-L"]!,
      lunch3: scheduleEntries["Pass-1137-F"]!),
  Schedule(
      hour: 11,
      minute: 24,
      lunch1: scheduleEntries["E-1207-F"]!,
      lunch2: scheduleEntries["E-1134-L"]!,
      lunch3: scheduleEntries["E-1134-F"]!),
  Schedule(
      hour: 11,
      minute: 21,
      lunch1: scheduleEntries["Pass-1124-E"]!,
      lunch2: scheduleEntries["E-1134-L"]!,
      lunch3: scheduleEntries["E-1134-F"]!),
  Schedule(
      hour: 10,
      minute: 51,
      lunch1: scheduleEntries["L-1121-E"]!,
      lunch2: scheduleEntries["E-1134-L"]!,
      lunch3: scheduleEntries["E-1134-F"]!),
  Schedule(
      hour: 10,
      minute: 48,
      lunch1: scheduleEntries["Pass-1051-L"]!,
      lunch2: scheduleEntries["Pass-1051-E"]!,
      lunch3: scheduleEntries["Pass-1051-E"]!),
  Schedule(
      hour: 10,
      minute: 0,
      lunch1: scheduleEntries["D-1048-L"]!,
      lunch2: scheduleEntries["D-1048-E"]!,
      lunch3: scheduleEntries["D-1048-E"]!),
  Schedule(
      hour: 9,
      minute: 58,
      lunch1: scheduleEntries["Second-1000-D"]!,
      lunch2: scheduleEntries["Second-1000-D"]!,
      lunch3: scheduleEntries["Second-1000-D"]!),
  Schedule(
      hour: 9,
      minute: 55,
      lunch1: scheduleEntries["Pass-1000-D"]!,
      lunch2: scheduleEntries["Pass-1000-D"]!,
      lunch3: scheduleEntries["Pass-1000-D"]!),
  Schedule(
      hour: 9,
      minute: 50,
      lunch1: scheduleEntries["First-1000-D"]!,
      lunch2: scheduleEntries["First-1000-D"]!,
      lunch3: scheduleEntries["First-1000-D"]!),
  Schedule(
      hour: 9,
      minute: 0,
      lunch1: scheduleEntries["Open-1000-D"]!,
      lunch2: scheduleEntries["Open-1000-D"]!,
      lunch3: scheduleEntries["Open-1000-D"]!),
];

List<Schedule> delayedStart250314List = [
  Schedule(
      hour: 13,
      minute: 29,
      lunch1: scheduleEntries["H-1424-Fin"]!,
      lunch2: scheduleEntries["H-1424-Fin"]!,
      lunch3: scheduleEntries["H-1424-Fin"]!),
  Schedule(
      hour: 13,
      minute: 26,
      lunch1: scheduleEntries["Pass-1329-H"]!,
      lunch2: scheduleEntries["Pass-1329-H"]!,
      lunch3: scheduleEntries["Pass-1329-H"]!),
  Schedule(
      hour: 12,
      minute: 56,
      lunch1: scheduleEntries["G-1326-H"]!,
      lunch2: scheduleEntries["G-1326-H"]!,
      lunch3: scheduleEntries["L-1326-H"]!),
  Schedule(
      hour: 12,
      minute: 53,
      lunch1: scheduleEntries["G-1326-H"]!,
      lunch2: scheduleEntries["G-1326-H"]!,
      lunch3: scheduleEntries["Pass-1256-L"]!),
  Schedule(
      hour: 12,
      minute: 31,
      lunch1: scheduleEntries["G-1326-H"]!,
      lunch2: scheduleEntries["G-1326-H"]!,
      lunch3: scheduleEntries["G-1253-L"]!),
  Schedule(
      hour: 12,
      minute: 28,
      lunch1: scheduleEntries["Pass-1231-G"]!,
      lunch2: scheduleEntries["Pass-1231-G"]!,
      lunch3: scheduleEntries["G-1253-L"]!),
  Schedule(
      hour: 11,
      minute: 58,
      lunch1: scheduleEntries["F-1228-G"]!,
      lunch2: scheduleEntries["L-1228-G"]!,
      lunch3: scheduleEntries["G-1253-L"]!),
  Schedule(
      hour: 11,
      minute: 55,
      lunch1: scheduleEntries["F-1228-G"]!,
      lunch2: scheduleEntries["Pass-1158-L"]!,
      lunch3: scheduleEntries["Pass-1158-G"]!),
  Schedule(
      hour: 11,
      minute: 33,
      lunch1: scheduleEntries["F-1228-G"]!,
      lunch2: scheduleEntries["F-1155-L"]!,
      lunch3: scheduleEntries["F-1155-G"]!),
  Schedule(
      hour: 11,
      minute: 30,
      lunch1: scheduleEntries["Pass-1133-F"]!,
      lunch2: scheduleEntries["F-1155-L"]!,
      lunch3: scheduleEntries["F-1155-G"]!),
  Schedule(
      hour: 11,
      minute: 0,
      lunch1: scheduleEntries["L-1130-F"]!,
      lunch2: scheduleEntries["F-1155-L"]!,
      lunch3: scheduleEntries["F-1155-G"]!),
  Schedule(
      hour: 10,
      minute: 57,
      lunch1: scheduleEntries["Pass-1100-L"]!,
      lunch2: scheduleEntries["Pass-1100-F"]!,
      lunch3: scheduleEntries["Pass-1100-F"]!),
  Schedule(
      hour: 10,
      minute: 0,
      lunch1: scheduleEntries["D-1057-L"]!,
      lunch2: scheduleEntries["D-1057-F"]!,
      lunch3: scheduleEntries["D-1057-F"]!),
  Schedule(
      hour: 9,
      minute: 58,
      lunch1: scheduleEntries["Second-1000-D"]!,
      lunch2: scheduleEntries["Second-1000-D"]!,
      lunch3: scheduleEntries["Second-1000-D"]!),
  Schedule(
      hour: 9,
      minute: 55,
      lunch1: scheduleEntries["Pass-1000-D"]!,
      lunch2: scheduleEntries["Pass-1000-D"]!,
      lunch3: scheduleEntries["Pass-1000-D"]!),
  Schedule(
      hour: 9,
      minute: 50,
      lunch1: scheduleEntries["First-1000-D"]!,
      lunch2: scheduleEntries["First-1000-D"]!,
      lunch3: scheduleEntries["First-1000-D"]!),
  Schedule(
      hour: 9,
      minute: 0,
      lunch1: scheduleEntries["Open-1000-D"]!,
      lunch2: scheduleEntries["Open-1000-D"]!,
      lunch3: scheduleEntries["Open-1000-D"]!),
];

List<Schedule> pepRally241122List = [
  Schedule(
      hour: 13,
      minute: 24,
      lunch1: scheduleEntries["Pep-1424-Fin"]!,
      lunch2: scheduleEntries["Pep-1424-Fin"]!,
      lunch3: scheduleEntries["Pep-1424-Fin"]!),
  Schedule(
      hour: 13,
      minute: 21,
      lunch1: scheduleEntries["Pass-1324-Pep"]!,
      lunch2: scheduleEntries["Pass-1324-Pep"]!,
      lunch3: scheduleEntries["Pass-1324-Pep"]!),
  Schedule(
      hour: 12,
      minute: 33,
      lunch1: scheduleEntries["H-1321-Pep"]!,
      lunch2: scheduleEntries["H-1321-Pep"]!,
      lunch3: scheduleEntries["H-1321-Pep"]!),
  Schedule(
      hour: 12,
      minute: 30,
      lunch1: scheduleEntries["Pass-1233-H"]!,
      lunch2: scheduleEntries["Pass-1233-H"]!,
      lunch3: scheduleEntries["Pass-1233-H"]!),
  Schedule(
      hour: 12,
      minute: 00,
      lunch1: scheduleEntries["G-1230-H"]!,
      lunch2: scheduleEntries["G-1230-H"]!,
      lunch3: scheduleEntries["L-1230-H"]!),
  Schedule(
      hour: 11,
      minute: 57,
      lunch1: scheduleEntries["G-1230-H"]!,
      lunch2: scheduleEntries["G-1230-H"]!,
      lunch3: scheduleEntries["Pass-1200-L"]!),
  Schedule(
      hour: 11,
      minute: 42,
      lunch1: scheduleEntries["G-1230-H"]!,
      lunch2: scheduleEntries["G-1230-H"]!,
      lunch3: scheduleEntries["G-1157-L"]!),
  Schedule(
      hour: 11,
      minute: 39,
      lunch1: scheduleEntries["Pass-1142-G"]!,
      lunch2: scheduleEntries["Pass-1142-G"]!,
      lunch3: scheduleEntries["G-1157-L"]!),
  Schedule(
      hour: 11,
      minute: 09,
      lunch1: scheduleEntries["F-1139-G"]!,
      lunch2: scheduleEntries["L-1139-G"]!,
      lunch3: scheduleEntries["G-1157-L"]!),
  Schedule(
      hour: 11,
      minute: 06,
      lunch1: scheduleEntries["F-1139-G"]!,
      lunch2: scheduleEntries["Pass-1109-L"]!,
      lunch3: scheduleEntries["Pass-1109-G"]!),
  Schedule(
      hour: 10,
      minute: 51,
      lunch1: scheduleEntries["F-1139-G"]!,
      lunch2: scheduleEntries["F-1106-L"]!,
      lunch3: scheduleEntries["F-1106-G"]!),
  Schedule(
      hour: 10,
      minute: 48,
      lunch1: scheduleEntries["Pass-1051-F"]!,
      lunch2: scheduleEntries["F-1106-L"]!,
      lunch3: scheduleEntries["F-1106-G"]!),
  Schedule(
      hour: 10,
      minute: 18,
      lunch1: scheduleEntries["L-1048-F"]!,
      lunch2: scheduleEntries["F-1106-L"]!,
      lunch3: scheduleEntries["F-1106-G"]!),
  Schedule(
      hour: 10,
      minute: 15,
      lunch1: scheduleEntries["Pass-1018-L"]!,
      lunch2: scheduleEntries["Pass-1018-F"]!,
      lunch3: scheduleEntries["Pass-1018-F"]!),
  Schedule(
      hour: 9,
      minute: 27,
      lunch1: scheduleEntries["D-1015-L"]!,
      lunch2: scheduleEntries["D-1015-F"]!,
      lunch3: scheduleEntries["D-1015-F"]!),
  Schedule(
      hour: 9,
      minute: 24,
      lunch1: scheduleEntries["Pass-927-D"]!,
      lunch2: scheduleEntries["Pass-927-D"]!,
      lunch3: scheduleEntries["Pass-927-D"]!),
  Schedule(
      hour: 8,
      minute: 36,
      lunch1: scheduleEntries["C-924-D"]!,
      lunch2: scheduleEntries["C-924-D"]!,
      lunch3: scheduleEntries["C-924-D"]!),
  Schedule(
      hour: 8,
      minute: 33,
      lunch1: scheduleEntries["Pass-836-C"]!,
      lunch2: scheduleEntries["Pass-836-C"]!,
      lunch3: scheduleEntries["Pass-836-C"]!),
  Schedule(
      hour: 7,
      minute: 45,
      lunch1: scheduleEntries["B-833-C"]!,
      lunch2: scheduleEntries["B-833-C"]!,
      lunch3: scheduleEntries["B-833-C"]!),
  Schedule(
      hour: 7,
      minute: 43,
      lunch1: scheduleEntries["Second-745-B"]!,
      lunch2: scheduleEntries["Second-745-B"]!,
      lunch3: scheduleEntries["Second-745-B"]!),
  Schedule(
      hour: 7,
      minute: 40,
      lunch1: scheduleEntries["Pass-745-B"]!,
      lunch2: scheduleEntries["Pass-745-B"]!,
      lunch3: scheduleEntries["Pass-745-B"]!),
  Schedule(
      hour: 7,
      minute: 35,
      lunch1: scheduleEntries["First-745-B"]!,
      lunch2: scheduleEntries["First-745-B"]!,
      lunch3: scheduleEntries["First-745-B"]!),
  Schedule(
      hour: 6,
      minute: 45,
      lunch1: scheduleEntries["Open-745-B"]!,
      lunch2: scheduleEntries["Open-745-B"]!,
      lunch3: scheduleEntries["Open-745-B"]!),
];