import 'package:lmmhsclock/domain/class_schedule_entry.dart';

Map<String, ScheduleEntry> scheduleEntries = {
  /// Monday
  "Open-745-A": ScheduleEntry(current: "Doors Open", ends: "7:45", next: "A"),
  "First-745-A": ScheduleEntry(current: "1st Bell", ends: "7:45", next: "A"),
  "Pass-745-A": ScheduleEntry(current: "Passing", ends: "7:45", next: "A"),
  "Second-745-A": ScheduleEntry(current: "2nd Bell", ends: "7:45", next: "A"),

  "A-830-B": ScheduleEntry(current: "A", ends: "8:30", next: "B"),
  "Pass-833-B": ScheduleEntry(current: "Passing", ends: "8:33", next: "B"),
  "B-916-C": ScheduleEntry(current: "B", ends: "9:16", next: "C"),
  "Pass-919-C": ScheduleEntry(current: "Passing", ends: "9:19", next: "C"),
  "C-1002-D": ScheduleEntry(current: "C", ends: "10:02", next: "D"),
  "Pass-1005-D": ScheduleEntry(current: "Passing", ends: "10:05", next: "D"),
  // First Lunch
  "D-1048-L": ScheduleEntry(current: "D", ends: "10:48", next: "Lunch"),
  "Pass-1051-L": ScheduleEntry(current: "Passing", ends: "10:51", next: "Lunch"),
  "L-1121-E": ScheduleEntry(current: "Lunch", ends: "11:21", next: "E"),
  "Pass-1124-E": ScheduleEntry(current: "Passing", ends: "11:24", next: "E"),
  "E-1207-F": ScheduleEntry(current: "E", ends: "12:07", next: "F"),
  "Pass-1210-F": ScheduleEntry(current: "Passing", ends: "12:10", next: "F"),
  "F-1253-G": ScheduleEntry(current: "F", ends: "12:53", next: "G"),
  // Second Lunch
  "D-1048-E": ScheduleEntry(current: "D", ends: "10:48", next: "E"),
  "Pass-1051-E": ScheduleEntry(current: "Passing", ends: "10:51", next: "E"),
  "E-1134-L": ScheduleEntry(current: "E", ends: "11:34", next: "Lunch"),
  "Pass-1137-L": ScheduleEntry(current: "Passing", ends: "11:37", next: "Lunch"),
  "L-1207-F": ScheduleEntry(current: "Lunch", ends: "12:07", next: "F"),
  //Third Lunch
  "E-1134-F": ScheduleEntry(current: "E", ends: "11:34", next: "F"),
  "Pass-1137-F": ScheduleEntry(current: "Passing", ends: "11:37", next: "F"),
  "F-1220-L": ScheduleEntry(current: "F", ends: "12:20", next: "Lunch"),
  "Pass-1223-L": ScheduleEntry(current: "Passing", ends: "12:23", next: "Lunch"),
  "L-1253-G": ScheduleEntry(current: "Lunch", ends: "12:53", next: "G"),

  "Pass-1256-G": ScheduleEntry(current: "Passing", ends: "12:56", next: "G"),
  "G-1338-H": ScheduleEntry(current: "G", ends: "13:38", next: "H"),
  "Pass-1341-H": ScheduleEntry(current: "Passing", ends: "13:41", next: "H"),
  "H-1424-Fin": ScheduleEntry(current: "H", ends: "14:24", next: "Dismissal"),

  /// Tuesday - Friday
  "Open-745-B": ScheduleEntry(current: "Doors Open", ends: "7:45", next: "B"),
  "First-745-B": ScheduleEntry(current: "1st Bell", ends: "7:45", next: "B"),
  "Pass-745-B": ScheduleEntry(current: "Passing", ends: "7:45", next: "B"),
  "Second-745-B": ScheduleEntry(current: "2nd Bell", ends: "7:45", next: "B"),

  "A-845-B": ScheduleEntry(current: "A", ends: "8:45", next: "B"),
  "A-845-C": ScheduleEntry(current: "A", ends: "8:45", next: "C"),
  "B-845-C": ScheduleEntry(current: "B", ends: "8:45", next: "C"),
  "Pass-848-B": ScheduleEntry(current: "Passing", ends: "8:48", next: "B"),
  "Pass-848-C": ScheduleEntry(current: "Passing", ends: "8:48", next: "C"),
  "B-946-C": ScheduleEntry(current: "B", ends: "9:46", next: "C"),
  "B-946-D": ScheduleEntry(current: "B", ends: "9:46", next: "D"),
  "C-946-D": ScheduleEntry(current: "C", ends: "9:46", next: "D"),
  "Pass-949-C": ScheduleEntry(current: "Passing", ends: "9:49", next: "C"),
  "Pass-949-D": ScheduleEntry(current: "Passing", ends: "9:49", next: "D"),
  // First Lunch
  "C-1047-L": ScheduleEntry(current: "C", ends: "10:47", next: "Lunch"),
  "D-1047-L": ScheduleEntry(current: "D", ends: "10:47", next: "Lunch"),
  "Pass-1050-L": ScheduleEntry(current: "Passing", ends: "10:50", next: "Lunch"),
  "L-1120-E": ScheduleEntry(current: "Lunch", ends: "11:20", next: "E"),
  "L-1120-F": ScheduleEntry(current: "Lunch", ends: "11:20", next: "F"),
  "Pass-1123-E": ScheduleEntry(current: "Passing", ends: "11:23", next: "E"),
  "Pass-1123-F": ScheduleEntry(current: "Passing", ends: "11:23", next: "F"),
  "E-1221-F": ScheduleEntry(current: "E", ends: "12:21", next: "F"),
  "E-1221-G": ScheduleEntry(current: "E", ends: "12:21", next: "G"),
  "F-1221-G": ScheduleEntry(current: "F", ends: "12:21", next: "G"),
  "Pass-1224-F": ScheduleEntry(current: "Passing", ends: "12:24", next: "F"),
  "Pass-1224-G": ScheduleEntry(current: "Passing", ends: "12:24", next: "G"),
  "F-1322-G": ScheduleEntry(current: "F", ends: "13:22", next: "G"),
  "F-1322-H": ScheduleEntry(current: "F", ends: "13:22", next: "H"),
  "G-1322-H": ScheduleEntry(current: "G", ends: "13:22", next: "H"),
  // Second Lunch
  "C-1047-E": ScheduleEntry(current: "C", ends: "10:47", next: "E"),
  "D-1047-E": ScheduleEntry(current: "D", ends: "10:47", next: "E"),
  "D-1047-F": ScheduleEntry(current: "D", ends: "10:47", next: "F"),
  "Pass-1050-E": ScheduleEntry(current: "Passing", ends: "10:50", next: "E"),
  "Pass-1050-F": ScheduleEntry(current: "Passing", ends: "10:50", next: "F"),
  "E-1148-L": ScheduleEntry(current: "E", ends: "11:48", next: "Lunch"),
  "F-1148-L": ScheduleEntry(current: "F", ends: "11:48", next: "Lunch"),
  "Pass-1151-L": ScheduleEntry(current: "Passing", ends: "11:51", next: "Lunch"),
  "L-1221-F": ScheduleEntry(current: "Lunch", ends: "12:21", next: "F"),
  "L-1221-G": ScheduleEntry(current: "Lunch", ends: "12:21", next: "G"),
  // Third Lunch
  "E-1148-F": ScheduleEntry(current: "E", ends: "11:48", next: "F"),
  "E-1148-G": ScheduleEntry(current: "E", ends: "11:48", next: "G"),
  "F-1148-G": ScheduleEntry(current: "F", ends: "11:48", next: "G"),
  "Pass-1151-F": ScheduleEntry(current: "Passing", ends: "11:51", next: "F"),
  "Pass-1151-G": ScheduleEntry(current: "Passing", ends: "11:51", next: "G"),
  "F-1249-L": ScheduleEntry(current: "F", ends: "12:49", next: "Lunch"),
  "G-1249-L": ScheduleEntry(current: "G", ends: "12:49", next: "Lunch"),
  "Pass-1252-L": ScheduleEntry(current: "Passing", ends: "12:52", next: "Lunch"),
  "L-1322-G": ScheduleEntry(current: "Lunch", ends: "13:22", next: "G"),
  "L-1322-H": ScheduleEntry(current: "Lunch", ends: "13:22", next: "H"),

  "Pass-1326-G": ScheduleEntry(current: "Passing", ends: "13:26", next: "G"),
  "Pass-1326-H": ScheduleEntry(current: "Passing", ends: "13:26", next: "H"),
  "G-1424-Fin": ScheduleEntry(current: "G", ends: "14:24", next: "Dismissal"),

  /// Early Dismissal - November 1, 2024
  "B-835-C": ScheduleEntry(current: "B", ends: "8:35", next: "C"),
  "Pass-838-C": ScheduleEntry(current: "Passing", ends: "8:38", next: "C"),
  "C-928-D": ScheduleEntry(current: "C", ends: "9:28", next: "D"),
  "Pass-931-D": ScheduleEntry(current: "Passing", ends: "9:31", next: "D"),
  "D-1021-F": ScheduleEntry(current: "D", ends: "10:21", next: "F"),
  "Pass-1024-F": ScheduleEntry(current: "Passing", ends: "10:24", next: "F"),
  "F-1115-Fin": ScheduleEntry(current: "F", ends: "11:15", next: "Dismissal"),

  /// Early Dismissal - April 18, 2024
  "A-809-B": ScheduleEntry(current: "A", ends: "8:09", next: "B"),
  "Pass-812-B": ScheduleEntry(current: "Passing", ends: "8:12", next: "B"),
  "B-836-C": ScheduleEntry(current: "B", ends: "8:36", next: "C"),
  "Pass-839-C": ScheduleEntry(current: "Passing", ends: "8:39", next: "C"),
  "C-902-D": ScheduleEntry(current: "C", ends: "9:02", next: "D"),
  "Pass-905-D": ScheduleEntry(current: "Passing", ends: "9:05", next: "D"),
  "D-929-E": ScheduleEntry(current: "D", ends: "9:29", next: "E"),
  "Pass-932-E": ScheduleEntry(current: "Passing", ends: "9:32", next: "E"),
  "E-955-F": ScheduleEntry(current: "E", ends: "9:55", next: "F"),
  "Pass-958-F": ScheduleEntry(current: "Passing", ends: "9:58", next: "F"),
  "F-1022-G": ScheduleEntry(current: "F", ends: "10:22", next: "G"),
  "Pass-1025-G": ScheduleEntry(current: "Passing", ends: "10:25", next: "G"),
  "G-1048-H": ScheduleEntry(current: "G", ends: "10:48", next: "H"),
  "Pass-1051-H": ScheduleEntry(current: "Passing", ends: "10:51", next: "H"),
  "H-1115-Fin": ScheduleEntry(current: "H", ends: "11:15", next: "Dismissal"),

  /// Late Arrival - October 28, 2024
  "Open-1000-D": ScheduleEntry(current: "Doors Open", ends: "10:00", next: "D"),
  "First-1000-D": ScheduleEntry(current: "1st Bell", ends: "10:00", next: "D"),
  "Pass-1000-D": ScheduleEntry(current: "Passing", ends: "10:00", next: "D"),
  "Second-1000-D": ScheduleEntry(current: "2nd Bell", ends: "10:00", next: "D"),

  /// Late Arrival - March 14, 2025
  // First Lunch
  "D-1057-L": ScheduleEntry(current: "D", ends: "10:57", next: "Lunch"),
  "Pass-1100-L": ScheduleEntry(current: "Passing", ends: "11:00", next: "Lunch"),
  "L-1130-F": ScheduleEntry(current: "Lunch", ends: "11:30", next: "F"),
  "Pass-1133-F": ScheduleEntry(current: "Passing", ends: "11:33", next: "F"),
  "F-1228-G": ScheduleEntry(current: "F", ends: "12:28", next: "G"),
  "Pass-1231-G": ScheduleEntry(current: "Passing", ends: "12:31", next: "G"),
  "G-1326-H": ScheduleEntry(current: "G", ends: "13:26", next: "H"),
  "Pass-1329-H": ScheduleEntry(current: "Passing", ends: "13:29", next: "H"),
  // Second Lunch
  "D-1057-E": ScheduleEntry(current: "D", ends: "10:57", next: "F"),
  "Pass-1100-F": ScheduleEntry(current: "Passing", ends: "11:00", next: "F"),
  "F-1155-L": ScheduleEntry(current: "F", ends: "11:55", next: "Lunch"),
  "Pass-1158-L": ScheduleEntry(current: "Passing", ends: "11:58", next: "Lunch"),
  "L-1228-G": ScheduleEntry(current: "Lunch", ends: "12:28", next: "G"),
  // Third Lunch
  "F-1155-G": ScheduleEntry(current: "F", ends: "11:55", next: "G"),
  "Pass-1158-G": ScheduleEntry(current: "Passing", ends: "11:58", next: "G"),
  "G-1253-L": ScheduleEntry(current: "G", ends: "12:53", next: "Lunch"),
  "Pass-1256-L": ScheduleEntry(current: "Passing", ends: "12:56", next: "Lunch"),
  "L-1326-H": ScheduleEntry(current: "Lunch", ends: "13:26", next: "H"),

  /// Pep Rally - November 22, 2024
  "B-833-C": ScheduleEntry(current: "B", ends: "8:33", next: "C"),
  "Pass-836-C": ScheduleEntry(current: "Passing", ends: "8:36", next: "C"),
  "C-924-D": ScheduleEntry(current: "C", ends: "9:24", next: "D"),
  "Pass-927-D": ScheduleEntry(current: "Passing", ends: "9:27", next: "D"),
  // First Lunch
  "D-1015-L": ScheduleEntry(current: "D", ends: "10:15", next: "Lunch"),
  "Pass-1018-L": ScheduleEntry(current: "Passing", ends: "10:18", next: "Lunch"),
  "L-1048-F": ScheduleEntry(current: "Lunch", ends: "10:48", next: "F"),
  "Pass-1051-F": ScheduleEntry(current: "Passing", ends: "10:51", next: "F"),
  "F-1139-G": ScheduleEntry(current: "F", ends: "11:39", next: "G"),
  "Pass-1142-G": ScheduleEntry(current: "Passing", ends: "11:42", next: "G"),
  "G-1230-H": ScheduleEntry(current: "G", ends: "12:30", next: "H"),
  "Pass-1233-H": ScheduleEntry(current: "Passing", ends: "12:33", next: "H"),
  "H-1321-Pep": ScheduleEntry(current: "H", ends: "13:21", next: "Pep Rally!"),
  "Pass-1324-Pep": ScheduleEntry(current: "Passing", ends: "13:24", next: "Pep Rally!"),
  "Pep-1424-Fin": ScheduleEntry(current: "Pep Rally!", ends: "14:24", next: "Dismissal"),
  // Second Lunch
  "D-1015-F": ScheduleEntry(current: "D", ends: "10:15", next: "F"),
  "Pass-1018-F": ScheduleEntry(current: "Passing", ends: "10:18", next: "F"),
  "F-1106-L": ScheduleEntry(current: "F", ends: "11:06", next: "Lunch"),
  "Pass-1109-L": ScheduleEntry(current: "Passing", ends: "11:09", next: "Lunch"),
  "L-1139-G": ScheduleEntry(current: "Lunch", ends: "11:39", next: "G"),
  // Third Lunch
  "F-1106-G": ScheduleEntry(current: "F", ends: "11:06", next: "G"),
  "Pass-1109-G": ScheduleEntry(current: "Passing", ends: "11:09", next: "G"),
  "G-1157-L": ScheduleEntry(current: "G", ends: "11:57", next: "Lunch"),
  "Pass-1200-L": ScheduleEntry(current: "Passing", ends: "12:00", next: "Lunch"),
  "L-1230-H": ScheduleEntry(current: "Lunch", ends: "12:30", next: "H"),

  "Unknown": ScheduleEntry(current: "Unknown", ends: "23:59", next: "Unknown")
};
