import 'package:lmmhsclock/class_schedule_entry.dart';

Map<String, ScheduleEntry> scheduleEntries = {
  "A-830-B": ScheduleEntry(current: "A", ends: "8:30", next: "B"),
  "A-845-B": ScheduleEntry(current: "A", ends: "8:45", next: "B"),
  "A-845-C": ScheduleEntry(current: "A", ends: "8:45", next: "C"),
  "B-835-C": ScheduleEntry(current: "B", ends: "8:35", next: "C"),
  "B-845-C": ScheduleEntry(current: "B", ends: "8:45", next: "C"),
  "B-916-C": ScheduleEntry(current: "B", ends: "9:16", next: "C"),
  "B-946-C": ScheduleEntry(current: "B", ends: "9:46", next: "C"),
  "B-946-D": ScheduleEntry(current: "B", ends: "9:46", next: "D"),
  "C-1002-D": ScheduleEntry(current: "C", ends: "10:02", next: "D"),
  "C-1047-E": ScheduleEntry(current: "C", ends: "10:47", next: "E"),
  "C-1047-L": ScheduleEntry(current: "C", ends: "10:47", next: "Lunch"),
  "C-928-D": ScheduleEntry(current: "C", ends: "9:28", next: "D"),
  "C-946-D": ScheduleEntry(current: "C", ends: "9:46", next: "D"),
  "D-1021-F": ScheduleEntry(current: "D", ends: "10:21", next: "F"),
  "D-1047-E": ScheduleEntry(current: "D", ends: "10:47", next: "E"),
  "D-1047-F": ScheduleEntry(current: "D", ends: "10:47", next: "F"),
  "D-1047-L": ScheduleEntry(current: "D", ends: "10:47", next: "Lunch"),
  "D-1048-E": ScheduleEntry(current: "D", ends: "10:48", next: "E"),
  "D-1048-L": ScheduleEntry(current: "D", ends: "10:48", next: "Lunch"),
  "E-1134-F": ScheduleEntry(current: "E", ends: "11:34", next: "F"),
  "E-1134-L": ScheduleEntry(current: "E", ends: "11:34", next: "Lunch"),
  "E-1148-F": ScheduleEntry(current: "E", ends: "11:48", next: "F"),
  "E-1148-G": ScheduleEntry(current: "E", ends: "11:48", next: "G"),
  "E-1148-L": ScheduleEntry(current: "E", ends: "11:48", next: "Lunch"),
  "E-1221-F": ScheduleEntry(current: "E", ends: "12:21", next: "F"),
  "E-1221-G": ScheduleEntry(current: "E", ends: "12:21", next: "G"),
  "E-1207-F": ScheduleEntry(current: "E", ends: "12:07", next: "F"),
  "F-1115-Fin": ScheduleEntry(current: "F", ends: "11:15", next: "Dismissal"),
  "F-1148-G": ScheduleEntry(current: "F", ends: "11:48", next: "G"),
  "F-1148-L": ScheduleEntry(current: "F", ends: "11:48", next: "Lunch"),
  "F-1220-L": ScheduleEntry(current: "F", ends: "12:20", next: "Lunch"),
  "F-1221-G": ScheduleEntry(current: "F", ends: "12:21", next: "G"),
  "F-1249-L": ScheduleEntry(current: "F", ends: "12:49", next: "Lunch"),
  "F-1253-G": ScheduleEntry(current: "F", ends: "12:53", next: "G"),
  "F-1322-G": ScheduleEntry(current: "F", ends: "13:22", next: "G"),
  "F-1322-H": ScheduleEntry(current: "F", ends: "13:22", next: "H"),
  "First-745-A": ScheduleEntry(current: "1st Bell", ends: "7:45", next: "A"),
  "First-745-B": ScheduleEntry(current: "1st Bell", ends: "7:45", next: "B"),
  "G-1249-L": ScheduleEntry(current: "G", ends: "12:49", next: "Lunch"),
  "G-1322-H": ScheduleEntry(current: "G", ends: "13:22", next: "H"),
  "G-1338-H": ScheduleEntry(current: "G", ends: "13:38", next: "H"),
  "G-1424-Fin": ScheduleEntry(current: "G", ends: "14:24", next: "Dismissal"),
  "H-1115-Fin": ScheduleEntry(current: "H", ends: "11:15", next: "Dismissal"),
  "H-1424-Fin": ScheduleEntry(current: "H", ends: "14:24", next: "Dismissal"),
  "L-1120-E": ScheduleEntry(current: "Lunch", ends: "11:20", next: "E"),
  "L-1120-F": ScheduleEntry(current: "Lunch", ends: "11:20", next: "F"),
  "L-1121-E": ScheduleEntry(current: "Lunch", ends: "11:21", next: "E"),
  "L-1207-F": ScheduleEntry(current: "Lunch", ends: "12:07", next: "F"),
  "L-1221-F": ScheduleEntry(current: "Lunch", ends: "12:21", next: "F"),
  "L-1221-G": ScheduleEntry(current: "Lunch", ends: "12:21", next: "G"),
  "L-1253-G": ScheduleEntry(current: "Lunch", ends: "12:53", next: "G"),
  "L-1322-G": ScheduleEntry(current: "Lunch", ends: "13:22", next: "G"),
  "L-1322-H": ScheduleEntry(current: "Lunch", ends: "13:22", next: "H"),
  "Open-745-A": ScheduleEntry(current: "Doors Open", ends: "7:45", next: "A"),
  "Open-745-B": ScheduleEntry(current: "Doors Open", ends: "7:45", next: "B"),
  "Pass-1005-D": ScheduleEntry(current: "Passing", ends: "10:05", next: "D"),
  "Pass-1024-F": ScheduleEntry(current: "Passing", ends: "10:24", next: "F"),
  "Pass-1050-E": ScheduleEntry(current: "Passing", ends: "10:50", next: "E"),
  "Pass-1050-F": ScheduleEntry(current: "Passing", ends: "10:50", next: "F"),
  "Pass-1050-L":
      ScheduleEntry(current: "Passing", ends: "10:50", next: "Lunch"),
  "Pass-1051-E": ScheduleEntry(current: "Passing", ends: "10:51", next: "E"),
  "Pass-1051-L":
      ScheduleEntry(current: "Passing", ends: "10:51", next: "Lunch"),
  "Pass-1123-E": ScheduleEntry(current: "Passing", ends: "11:23", next: "E"),
  "Pass-1123-F": ScheduleEntry(current: "Passing", ends: "11:23", next: "F"),
  "Pass-1124-E": ScheduleEntry(current: "Passing", ends: "11:24", next: "E"),
  "Pass-1137-F": ScheduleEntry(current: "Passing", ends: "11:37", next: "F"),
  "Pass-1137-L":
      ScheduleEntry(current: "Passing", ends: "11:37", next: "Lunch"),
  "Pass-1151-F": ScheduleEntry(current: "Passing", ends: "11:51", next: "F"),
  "Pass-1151-G": ScheduleEntry(current: "Passing", ends: "11:51", next: "G"),
  "Pass-1151-L":
      ScheduleEntry(current: "Passing", ends: "11:51", next: "Lunch"),
  "Pass-1210-F": ScheduleEntry(current: "Passing", ends: "12:10", next: "F"),
  "Pass-1223-L":
      ScheduleEntry(current: "Passing", ends: "12:23", next: "Lunch"),
  "Pass-1224-F": ScheduleEntry(current: "Passing", ends: "12:24", next: "F"),
  "Pass-1224-G": ScheduleEntry(current: "Passing", ends: "12:24", next: "G"),
  "Pass-1252-L":
      ScheduleEntry(current: "Passing", ends: "12:52", next: "Lunch"),
  "Pass-1256-G": ScheduleEntry(current: "Passing", ends: "12:56", next: "G"),
  "Pass-1326-G": ScheduleEntry(current: "Passing", ends: "13:26", next: "G"),
  "Pass-1326-H": ScheduleEntry(current: "Passing", ends: "13:26", next: "H"),
  "Pass-1341-H": ScheduleEntry(current: "Passing", ends: "13:41", next: "H"),
  "Pass-745-A": ScheduleEntry(current: "Passing", ends: "7:45", next: "A"),
  "Pass-745-B": ScheduleEntry(current: "Passing", ends: "7:45", next: "B"),
  "Pass-833-B": ScheduleEntry(current: "Passing", ends: "8:33", next: "B"),
  "Pass-838-C": ScheduleEntry(current: "Passing", ends: "8:38", next: "C"),
  "Pass-848-B": ScheduleEntry(current: "Passing", ends: "8:48", next: "B"),
  "Pass-848-C": ScheduleEntry(current: "Passing", ends: "8:48", next: "C"),
  "Pass-919-C": ScheduleEntry(current: "Passing", ends: "9:19", next: "C"),
  "Pass-931-D": ScheduleEntry(current: "Passing", ends: "9:31", next: "D"),
  "Pass-949-C": ScheduleEntry(current: "Passing", ends: "9:49", next: "C"),
  "Pass-949-D": ScheduleEntry(current: "Passing", ends: "9:49", next: "D"),
  "Second-745-A": ScheduleEntry(current: "2nd Bell", ends: "7:45", next: "A"),
  "Second-745-B": ScheduleEntry(current: "2nd Bell", ends: "7:45", next: "B"),
  "Second-1000-D": ScheduleEntry(current: "2nd Bell", ends: "10:00", next: "D"),
  "Pass-1000-D": ScheduleEntry(current: "Passing", ends: "10:00", next: "D"),
  "First-1000-D": ScheduleEntry(current: "1st Bell", ends: "10:00", next: "D"),
  "Open-1000-D": ScheduleEntry(current: "Doors Open", ends: "10:00", next: "D"),
  "Pass-1051-H": ScheduleEntry(current: "Passing", ends: "10:51", next: "H"),
  "G-1048-H": ScheduleEntry(current: "G", ends: "10:48", next: "H"),
  "Pass-1025-G": ScheduleEntry(current: "Passing", ends: "10:25", next: "G"),
  "F-1022-G": ScheduleEntry(current: "F", ends: "10:22", next: "G"),
  "Pass-958-F": ScheduleEntry(current: "Passing", ends: "9:58", next: "F"),
  "E-955-F": ScheduleEntry(current: "E", ends: "9:55", next: "F"),
  "Pass-932-E": ScheduleEntry(current: "Passing", ends: "9:32", next: "E"),
  "D-929-E": ScheduleEntry(current: "D", ends: "9:29", next: "E"),
  "Pass-905-D": ScheduleEntry(current: "Passing", ends: "9:05", next: "D"),
  "C-902-D": ScheduleEntry(current: "C", ends: "9:02", next: "D"),
  "Pass-839-C": ScheduleEntry(current: "Passing", ends: "8:39", next: "C"),
  "B-836-C": ScheduleEntry(current: "B", ends: "8:36", next: "C"),
  "Pass-812-B": ScheduleEntry(current: "Passing", ends: "8:12", next: "B"),
  "A-809-B": ScheduleEntry(current: "A", ends: "8:09", next: "B"),
  "Unknown": ScheduleEntry(current: "Unknown", ends: "23:59", next: "Unknown")
};
