import 'class_schedule.dart';

List<Schedule> mondayList = [
  Schedule(
      hour: 13,
      minute: 41,
      firstCurrent: "H",
      firstNext: "Let Out",
      firstDateTime: "14:24",
      secondCurrent: "H",
      secondNext: "Let Out",
      secondDateTime: "14:24",
      thirdCurrent: "H",
      thirdNext: "Let Out",
      thirdDateTime: "14:24"),
  Schedule(
      hour: 13,
      minute: 38,
      firstCurrent: "Passing",
      firstNext: "H",
      firstDateTime: "13:41",
      secondCurrent: "Passing",
      secondNext: "H",
      secondDateTime: "13:41",
      thirdCurrent: "Passing",
      thirdNext: "H",
      thirdDateTime: "13:41"),
  Schedule(
      hour: 12,
      minute: 56,
      firstCurrent: "G",
      firstNext: "H",
      firstDateTime: "13:38",
      secondCurrent: "G",
      secondNext: "H",
      secondDateTime: "13:38",
      thirdCurrent: "G",
      thirdNext: "H",
      thirdDateTime: "13:38"),
  Schedule(
      hour: 12,
      minute: 53,
      firstCurrent: "Passing",
      firstNext: "G",
      firstDateTime: "12:56",
      secondCurrent: "Passing",
      secondNext: "G",
      secondDateTime: "12:56",
      thirdCurrent: "Passing",
      thirdNext: "G",
      thirdDateTime: "12:56"),
  Schedule(
      hour: 12,
      minute: 23,
      firstCurrent: "F",
      firstNext: "G",
      firstDateTime: "12:53",
      secondCurrent: "F",
      secondNext: "G",
      secondDateTime: "12:53",
      thirdCurrent: "Lunch",
      thirdNext: "G",
      thirdDateTime: "12:53"),
  Schedule(
      hour: 12,
      minute: 20,
      firstCurrent: "F",
      firstNext: "G",
      firstDateTime: "12:53",
      secondCurrent: "F",
      secondNext: "G",
      secondDateTime: "12:53",
      thirdCurrent: "Passing",
      thirdNext: "Lunch",
      thirdDateTime: "12:23"),
  Schedule(
      hour: 12,
      minute: 10,
      firstCurrent: "F",
      firstNext: "G",
      firstDateTime: "12:53",
      secondCurrent: "F",
      secondNext: "G",
      secondDateTime: "12:53",
      thirdCurrent: "F",
      thirdNext: "Lunch",
      thirdDateTime: "12:20"),
  Schedule(
      hour: 12,
      minute: 07,
      firstCurrent: "Passing",
      firstNext: "F",
      firstDateTime: "12:10",
      secondCurrent: "Passing",
      secondNext: "F",
      secondDateTime: "12:10",
      thirdCurrent: "F",
      thirdNext: "Lunch",
      thirdDateTime: "12:20"),
  Schedule(
      hour: 11,
      minute: 37,
      firstCurrent: "E",
      firstNext: "F",
      firstDateTime: "12:07",
      secondCurrent: "Lunch",
      secondNext: "F",
      secondDateTime: "12:07",
      thirdCurrent: "F",
      thirdNext: "Lunch",
      thirdDateTime: "12:20"),
  Schedule(
      hour: 11,
      minute: 34,
      firstCurrent: "E",
      firstNext: "F",
      firstDateTime: "12:07",
      secondCurrent: "Passing",
      secondNext: "Lunch",
      secondDateTime: "11:37",
      thirdCurrent: "Passing",
      thirdNext: "F",
      thirdDateTime: "11:37"),
  Schedule(
      hour: 11,
      minute: 24,
      firstCurrent: "E",
      firstNext: "F",
      firstDateTime: "12:07",
      secondCurrent: "E",
      secondNext: "Lunch",
      secondDateTime: "11:34",
      thirdCurrent: "E",
      thirdNext: "F",
      thirdDateTime: "11:34"),
  Schedule(
      hour: 11,
      minute: 21,
      firstCurrent: "Passing",
      firstNext: "E",
      firstDateTime: "11:24",
      secondCurrent: "E",
      secondNext: "Lunch",
      secondDateTime: "11:34",
      thirdCurrent: "E",
      thirdNext: "F",
      thirdDateTime: "11:34"),
  Schedule(
      hour: 10,
      minute: 51,
      firstCurrent: "Lunch",
      firstNext: "E",
      firstDateTime: "11:21",
      secondCurrent: "E",
      secondNext: "Lunch",
      secondDateTime: "11:34",
      thirdCurrent: "E",
      thirdNext: "F",
      thirdDateTime: "11:34"),
  Schedule(
      hour: 10,
      minute: 48,
      firstCurrent: "Passing",
      firstNext: "Lunch",
      firstDateTime: "10:51",
      secondCurrent: "Passing",
      secondNext: "E",
      secondDateTime: "10:51",
      thirdCurrent: "Passing",
      thirdNext: "E",
      thirdDateTime: "10:51"),
  Schedule(
      hour: 10,
      minute: 05,
      firstCurrent: "D",
      firstNext: "Lunch",
      firstDateTime: "10:48",
      secondCurrent: "D",
      secondNext: "E",
      secondDateTime: "10:48",
      thirdCurrent: "D",
      thirdNext: "E",
      thirdDateTime: "10:48"),
  Schedule(
      hour: 10,
      minute: 02,
      firstCurrent: "Passing",
      firstNext: "D",
      firstDateTime: "10:05",
      secondCurrent: "Passing",
      secondNext: "D",
      secondDateTime: "10:05",
      thirdCurrent: "Passing",
      thirdNext: "D",
      thirdDateTime: "10:05"),
  Schedule(
      hour: 9,
      minute: 19,
      firstCurrent: "C",
      firstNext: "D",
      firstDateTime: "10:02",
      secondCurrent: "C",
      secondNext: "D",
      secondDateTime: "10:02",
      thirdCurrent: "C",
      thirdNext: "D",
      thirdDateTime: "10:02"),
  Schedule(
      hour: 9,
      minute: 16,
      firstCurrent: "Passing",
      firstNext: "C",
      firstDateTime: "9:19",
      secondCurrent: "Passing",
      secondNext: "C",
      secondDateTime: "9:19",
      thirdCurrent: "Passing",
      thirdNext: "C",
      thirdDateTime: "9:19"),
  Schedule(
      hour: 8,
      minute: 33,
      firstCurrent: "B",
      firstNext: "C",
      firstDateTime: "9:16",
      secondCurrent: "B",
      secondNext: "C",
      secondDateTime: "9:16",
      thirdCurrent: "B",
      thirdNext: "C",
      thirdDateTime: "9:16"),
  Schedule(
      hour: 8,
      minute: 30,
      firstCurrent: "Passing",
      firstNext: "B",
      firstDateTime: "8:33",
      secondCurrent: "Passing",
      secondNext: "B",
      secondDateTime: "8:33",
      thirdCurrent: "Passing",
      thirdNext: "B",
      thirdDateTime: "8:33"),
  Schedule(
      hour: 7,
      minute: 45,
      firstCurrent: "A",
      firstNext: "B",
      firstDateTime: "8:30",
      secondCurrent: "A",
      secondNext: "B",
      secondDateTime: "8:30",
      thirdCurrent: "A",
      thirdNext: "B",
      thirdDateTime: "8:30"),
  Schedule(
      hour: 7,
      minute: 43,
      firstCurrent: "2nd Bell",
      firstNext: "A",
      firstDateTime: "7:45",
      secondCurrent: "2nd Bell",
      secondNext: "A",
      secondDateTime: "7:45",
      thirdCurrent: "2nd Bell",
      thirdNext: "A",
      thirdDateTime: "7:45"),
  Schedule(
      hour: 7,
      minute: 40,
      firstCurrent: "Passing",
      firstNext: "A",
      firstDateTime: "7:45",
      secondCurrent: "Passing",
      secondNext: "A",
      secondDateTime: "7:45",
      thirdCurrent: "Passing",
      thirdNext: "A",
      thirdDateTime: "7:45"),
  Schedule(
      hour: 7,
      minute: 35,
      firstCurrent: "Opening",
      firstNext: "A",
      firstDateTime: "7:45",
      secondCurrent: "Opening",
      secondNext: "A",
      secondDateTime: "7:45",
      thirdCurrent: "Opening",
      thirdNext: "A",
      thirdDateTime: "7:45"),
  Schedule(
      hour: 6,
      minute: 45,
      firstCurrent: "Open",
      firstNext: "A",
      firstDateTime: "7:45",
      secondCurrent: "Open",
      secondNext: "A",
      secondDateTime: "7:45",
      thirdCurrent: "Open",
      thirdNext: "A",
      thirdDateTime: "7:45"),
];

List<Schedule> tuesdayList = [
  Schedule(
      hour: 13,
      minute: 26,
      firstCurrent: "H",
      firstNext: "Let Out",
      firstDateTime: "14:24",
      secondCurrent: "H",
      secondNext: "Let Out",
      secondDateTime: "14:24",
      thirdCurrent: "H",
      thirdNext: "Let Out",
      thirdDateTime: "14:24"),
  Schedule(
      hour: 13,
      minute: 22,
      firstCurrent: "Passing",
      firstNext: "H",
      firstDateTime: "13:26",
      secondCurrent: "Passing",
      secondNext: "H",
      secondDateTime: "13:26",
      thirdCurrent: "Passing",
      thirdNext: "H",
      thirdDateTime: "13:26"),
  Schedule(
      hour: 12,
      minute: 52,
      firstCurrent: "F",
      firstNext: "H",
      firstDateTime: "13:26",
      secondCurrent: "F",
      secondNext: "H",
      secondDateTime: "13:26",
      thirdCurrent: "Lunch",
      thirdNext: "H",
      thirdDateTime: "13:26"),
  Schedule(
      hour: 12,
      minute: 49,
      firstCurrent: "F",
      firstNext: "H",
      firstDateTime: "13:26",
      secondCurrent: "F",
      secondNext: "H",
      secondDateTime: "13:26",
      thirdCurrent: "Passing",
      thirdNext: "Lunch",
      thirdDateTime: "12:52"),
  Schedule(
      hour: 12,
      minute: 24,
      firstCurrent: "F",
      firstNext: "H",
      firstDateTime: "13:26",
      secondCurrent: "F",
      secondNext: "H",
      secondDateTime: "13:26",
      thirdCurrent: "F",
      thirdNext: "Lunch",
      thirdDateTime: "12:49"),
  Schedule(
      hour: 12,
      minute: 21,
      firstCurrent: "Passing",
      firstNext: "F",
      firstDateTime: "12:24",
      secondCurrent: "Passing",
      secondNext: "F",
      secondDateTime: "12:24",
      thirdCurrent: "F",
      thirdNext: "Lunch",
      thirdDateTime: "12:49"),
  Schedule(
      hour: 11,
      minute: 51,
      firstCurrent: "E",
      firstNext: "F",
      firstDateTime: "12:21",
      secondCurrent: "Lunch",
      secondNext: "F",
      secondDateTime: "12:21",
      thirdCurrent: "F",
      thirdNext: "Lunch",
      thirdDateTime: "12:49"),
  Schedule(
      hour: 11,
      minute: 48,
      firstCurrent: "E",
      firstNext: "F",
      firstDateTime: "12:21",
      secondCurrent: "Passing",
      secondNext: "Lunch",
      secondDateTime: "11:51",
      thirdCurrent: "Passing",
      thirdNext: "F",
      thirdDateTime: "11:51"),
  Schedule(
      hour: 11,
      minute: 23,
      firstCurrent: "E",
      firstNext: "F",
      firstDateTime: "12:21",
      secondCurrent: "E",
      secondNext: "Lunch",
      secondDateTime: "11:48",
      thirdCurrent: "E",
      thirdNext: "F",
      thirdDateTime: "11:48"),
  Schedule(
      hour: 11,
      minute: 20,
      firstCurrent: "Passing",
      firstNext: "E",
      firstDateTime: "11:23",
      secondCurrent: "E",
      secondNext: "Lunch",
      secondDateTime: "11:48",
      thirdCurrent: "E",
      thirdNext: "F",
      thirdDateTime: "11:48"),
  Schedule(
      hour: 10,
      minute: 50,
      firstCurrent: "Lunch",
      firstNext: "E",
      firstDateTime: "11:20",
      secondCurrent: "E",
      secondNext: "Lunch",
      secondDateTime: "11:48",
      thirdCurrent: "E",
      thirdNext: "F",
      thirdDateTime: "11:48"),
  Schedule(
      hour: 10,
      minute: 47,
      firstCurrent: "Passing",
      firstNext: "Lunch",
      firstDateTime: "10:50",
      secondCurrent: "Passing",
      secondNext: "E",
      secondDateTime: "10:50",
      thirdCurrent: "Passing",
      thirdNext: "E",
      thirdDateTime: "10:50"),
  Schedule(
      hour: 9,
      minute: 49,
      firstCurrent: "D",
      firstNext: "Lunch",
      firstDateTime: "10:47",
      secondCurrent: "D",
      secondNext: "E",
      secondDateTime: "10:47",
      thirdCurrent: "D",
      thirdNext: "E",
      thirdDateTime: "10:47"),
  Schedule(
      hour: 9,
      minute: 46,
      firstCurrent: "Passing",
      firstNext: "D",
      firstDateTime: "9:49",
      secondCurrent: "Passing",
      secondNext: "D",
      secondDateTime: "9:49",
      thirdCurrent: "Passing",
      thirdNext: "D",
      thirdDateTime: "9:49"),
  Schedule(
      hour: 8,
      minute: 48,
      firstCurrent: "B",
      firstNext: "D",
      firstDateTime: "9:46",
      secondCurrent: "B",
      secondNext: "D",
      secondDateTime: "9:46",
      thirdCurrent: "B",
      thirdNext: "D",
      thirdDateTime: "9:46"),
  Schedule(
      hour: 8,
      minute: 45,
      firstCurrent: "Passing",
      firstNext: "B",
      firstDateTime: "8:48",
      secondCurrent: "Passing",
      secondNext: "B",
      secondDateTime: "8:48",
      thirdCurrent: "Passing",
      thirdNext: "B",
      thirdDateTime: "8:48"),
  Schedule(
      hour: 7,
      minute: 45,
      firstCurrent: "A",
      firstNext: "B",
      firstDateTime: "8:45",
      secondCurrent: "A",
      secondNext: "B",
      secondDateTime: "8:45",
      thirdCurrent: "A",
      thirdNext: "B",
      thirdDateTime: "8:45"),
  Schedule(
      hour: 7,
      minute: 43,
      firstCurrent: "2nd Bell",
      firstNext: "A",
      firstDateTime: "7:45",
      secondCurrent: "2nd Bell",
      secondNext: "A",
      secondDateTime: "7:45",
      thirdCurrent: "2nd Bell",
      thirdNext: "A",
      thirdDateTime: "7:45"),
  Schedule(
      hour: 7,
      minute: 40,
      firstCurrent: "Passing",
      firstNext: "A",
      firstDateTime: "7:45",
      secondCurrent: "Passing",
      secondNext: "A",
      secondDateTime: "7:45",
      thirdCurrent: "Passing",
      thirdNext: "A",
      thirdDateTime: "7:45"),
  Schedule(
      hour: 7,
      minute: 35,
      firstCurrent: "Opening",
      firstNext: "A",
      firstDateTime: "7:45",
      secondCurrent: "Opening",
      secondNext: "A",
      secondDateTime: "7:45",
      thirdCurrent: "Opening",
      thirdNext: "A",
      thirdDateTime: "7:45"),
  Schedule(
      hour: 6,
      minute: 45,
      firstCurrent: "Open",
      firstNext: "A",
      firstDateTime: "7:45",
      secondCurrent: "Open",
      secondNext: "A",
      secondDateTime: "7:45",
      thirdCurrent: "Open",
      thirdNext: "A",
      thirdDateTime: "7:45"),
];

List<Schedule> wednesdayList = [
  Schedule(
      hour: 13,
      minute: 26,
      firstCurrent: "H",
      firstNext: "Let Out",
      firstDateTime: "14:24",
      secondCurrent: "H",
      secondNext: "Let Out",
      secondDateTime: "14:24",
      thirdCurrent: "H",
      thirdNext: "Let Out",
      thirdDateTime: "14:24"),
  Schedule(
      hour: 13,
      minute: 22,
      firstCurrent: "Passing",
      firstNext: "H",
      firstDateTime: "13:26",
      secondCurrent: "Passing",
      secondNext: "H",
      secondDateTime: "13:26",
      thirdCurrent: "Passing",
      thirdNext: "H",
      thirdDateTime: "13:26"),
  Schedule(
      hour: 12,
      minute: 52,
      firstCurrent: "G",
      firstNext: "H",
      firstDateTime: "13:22",
      secondCurrent: "G",
      secondNext: "H",
      secondDateTime: "13:22",
      thirdCurrent: "Lunch",
      thirdNext: "H",
      thirdDateTime: "13:22"),
  Schedule(
      hour: 12,
      minute: 49,
      firstCurrent: "G",
      firstNext: "H",
      firstDateTime: "13:26",
      secondCurrent: "G",
      secondNext: "H",
      secondDateTime: "13:26",
      thirdCurrent: "Passing",
      thirdNext: "Lunch",
      thirdDateTime: "12:52"),
  Schedule(
      hour: 12,
      minute: 24,
      firstCurrent: "G",
      firstNext: "H",
      firstDateTime: "13:26",
      secondCurrent: "G",
      secondNext: "H",
      secondDateTime: "13:26",
      thirdCurrent: "G",
      thirdNext: "Lunch",
      thirdDateTime: "12:49"),
  Schedule(
      hour: 12,
      minute: 21,
      firstCurrent: "Passing",
      firstNext: "G",
      firstDateTime: "12:24",
      secondCurrent: "Passing",
      secondNext: "G",
      secondDateTime: "12:24",
      thirdCurrent: "G",
      thirdNext: "Lunch",
      thirdDateTime: "12:49"),
  Schedule(
      hour: 11,
      minute: 51,
      firstCurrent: "E",
      firstNext: "G",
      firstDateTime: "12:21",
      secondCurrent: "Lunch",
      secondNext: "G",
      secondDateTime: "12:21",
      thirdCurrent: "G",
      thirdNext: "Lunch",
      thirdDateTime: "12:49"),
  Schedule(
      hour: 11,
      minute: 48,
      firstCurrent: "E",
      firstNext: "G",
      firstDateTime: "12:21",
      secondCurrent: "Passing",
      secondNext: "Lunch",
      secondDateTime: "11:51",
      thirdCurrent: "Passing",
      thirdNext: "G",
      thirdDateTime: "11:51"),
  Schedule(
      hour: 11,
      minute: 23,
      firstCurrent: "E",
      firstNext: "G",
      firstDateTime: "12:21",
      secondCurrent: "E",
      secondNext: "Lunch",
      secondDateTime: "11:48",
      thirdCurrent: "E",
      thirdNext: "G",
      thirdDateTime: "11:48"),
  Schedule(
      hour: 11,
      minute: 20,
      firstCurrent: "Passing",
      firstNext: "E",
      firstDateTime: "11:23",
      secondCurrent: "E",
      secondNext: "Lunch",
      secondDateTime: "11:48",
      thirdCurrent: "E",
      thirdNext: "G",
      thirdDateTime: "11:48"),
  Schedule(
      hour: 10,
      minute: 50,
      firstCurrent: "Lunch",
      firstNext: "E",
      firstDateTime: "11:20",
      secondCurrent: "E",
      secondNext: "Lunch",
      secondDateTime: "11:48",
      thirdCurrent: "E",
      thirdNext: "G",
      thirdDateTime: "11:48"),
  Schedule(
      hour: 10,
      minute: 47,
      firstCurrent: "Passing",
      firstNext: "Lunch",
      firstDateTime: "10:50",
      secondCurrent: "Passing",
      secondNext: "E",
      secondDateTime: "10:50",
      thirdCurrent: "Passing",
      thirdNext: "E",
      thirdDateTime: "10:50"),
  Schedule(
      hour: 9,
      minute: 49,
      firstCurrent: "D",
      firstNext: "Lunch",
      firstDateTime: "10:47",
      secondCurrent: "D",
      secondNext: "E",
      secondDateTime: "10:47",
      thirdCurrent: "D",
      thirdNext: "E",
      thirdDateTime: "10:47"),
  Schedule(
      hour: 9,
      minute: 46,
      firstCurrent: "Passing",
      firstNext: "D",
      firstDateTime: "9:49",
      secondCurrent: "Passing",
      secondNext: "D",
      secondDateTime: "9:49",
      thirdCurrent: "Passing",
      thirdNext: "D",
      thirdDateTime: "9:49"),
  Schedule(
      hour: 8,
      minute: 48,
      firstCurrent: "C",
      firstNext: "D",
      firstDateTime: "9:46",
      secondCurrent: "C",
      secondNext: "D",
      secondDateTime: "9:46",
      thirdCurrent: "C",
      thirdNext: "D",
      thirdDateTime: "9:46"),
  Schedule(
      hour: 8,
      minute: 45,
      firstCurrent: "Passing",
      firstNext: "C",
      firstDateTime: "8:48",
      secondCurrent: "Passing",
      secondNext: "C",
      secondDateTime: "8:48",
      thirdCurrent: "Passing",
      thirdNext: "C",
      thirdDateTime: "8:48"),
  Schedule(
      hour: 7,
      minute: 45,
      firstCurrent: "A",
      firstNext: "C",
      firstDateTime: "8:45",
      secondCurrent: "A",
      secondNext: "C",
      secondDateTime: "8:45",
      thirdCurrent: "A",
      thirdNext: "C",
      thirdDateTime: "8:45"),
  Schedule(
      hour: 7,
      minute: 43,
      firstCurrent: "2nd Bell",
      firstNext: "A",
      firstDateTime: "7:45",
      secondCurrent: "2nd Bell",
      secondNext: "A",
      secondDateTime: "7:45",
      thirdCurrent: "2nd Bell",
      thirdNext: "A",
      thirdDateTime: "7:45"),
  Schedule(
      hour: 7,
      minute: 40,
      firstCurrent: "Passing",
      firstNext: "A",
      firstDateTime: "7:45",
      secondCurrent: "Passing",
      secondNext: "A",
      secondDateTime: "7:45",
      thirdCurrent: "Passing",
      thirdNext: "A",
      thirdDateTime: "7:45"),
  Schedule(
      hour: 7,
      minute: 35,
      firstCurrent: "Opening",
      firstNext: "A",
      firstDateTime: "7:45",
      secondCurrent: "Opening",
      secondNext: "A",
      secondDateTime: "7:45",
      thirdCurrent: "Opening",
      thirdNext: "A",
      thirdDateTime: "7:45"),
  Schedule(
      hour: 6,
      minute: 45,
      firstCurrent: "Open",
      firstNext: "A",
      firstDateTime: "7:45",
      secondCurrent: "Open",
      secondNext: "A",
      secondDateTime: "7:45",
      thirdCurrent: "Open",
      thirdNext: "A",
      thirdDateTime: "7:45"),
];

List<Schedule> thursdayList = [
  Schedule(
      hour: 13,
      minute: 26,
      firstCurrent: "G",
      firstNext: "Let Out",
      firstDateTime: "14:24",
      secondCurrent: "G",
      secondNext: "Let Out",
      secondDateTime: "14:24",
      thirdCurrent: "G",
      thirdNext: "Let Out",
      thirdDateTime: "14:24"),
  Schedule(
      hour: 13,
      minute: 22,
      firstCurrent: "Passing",
      firstNext: "G",
      firstDateTime: "13:26",
      secondCurrent: "Passing",
      secondNext: "G",
      secondDateTime: "13:26",
      thirdCurrent: "Passing",
      thirdNext: "G",
      thirdDateTime: "13:26"),
  Schedule(
      hour: 12,
      minute: 52,
      firstCurrent: "F",
      firstNext: "G",
      firstDateTime: "13:26",
      secondCurrent: "F",
      secondNext: "G",
      secondDateTime: "13:26",
      thirdCurrent: "Lunch",
      thirdNext: "G",
      thirdDateTime: "13:26"),
  Schedule(
      hour: 12,
      minute: 49,
      firstCurrent: "F",
      firstNext: "G",
      firstDateTime: "13:26",
      secondCurrent: "F",
      secondNext: "G",
      secondDateTime: "13:26",
      thirdCurrent: "Passing",
      thirdNext: "Lunch",
      thirdDateTime: "12:52"),
  Schedule(
      hour: 12,
      minute: 24,
      firstCurrent: "F",
      firstNext: "G",
      firstDateTime: "13:26",
      secondCurrent: "F",
      secondNext: "G",
      secondDateTime: "13:26",
      thirdCurrent: "F",
      thirdNext: "Lunch",
      thirdDateTime: "12:49"),
  Schedule(
      hour: 12,
      minute: 21,
      firstCurrent: "Passing",
      firstNext: "F",
      firstDateTime: "12:24",
      secondCurrent: "Passing",
      secondNext: "F",
      secondDateTime: "12:24",
      thirdCurrent: "F",
      thirdNext: "Lunch",
      thirdDateTime: "12:49"),
  Schedule(
      hour: 11,
      minute: 51,
      firstCurrent: "E",
      firstNext: "F",
      firstDateTime: "12:21",
      secondCurrent: "Lunch",
      secondNext: "F",
      secondDateTime: "12:21",
      thirdCurrent: "F",
      thirdNext: "Lunch",
      thirdDateTime: "12:49"),
  Schedule(
      hour: 11,
      minute: 48,
      firstCurrent: "E",
      firstNext: "F",
      firstDateTime: "12:21",
      secondCurrent: "Passing",
      secondNext: "Lunch",
      secondDateTime: "11:51",
      thirdCurrent: "Passing",
      thirdNext: "F",
      thirdDateTime: "11:51"),
  Schedule(
      hour: 11,
      minute: 23,
      firstCurrent: "E",
      firstNext: "F",
      firstDateTime: "12:21",
      secondCurrent: "E",
      secondNext: "Lunch",
      secondDateTime: "11:48",
      thirdCurrent: "E",
      thirdNext: "F",
      thirdDateTime: "11:48"),
  Schedule(
      hour: 11,
      minute: 20,
      firstCurrent: "Passing",
      firstNext: "E",
      firstDateTime: "11:23",
      secondCurrent: "E",
      secondNext: "Lunch",
      secondDateTime: "11:48",
      thirdCurrent: "E",
      thirdNext: "F",
      thirdDateTime: "11:48"),
  Schedule(
      hour: 10,
      minute: 50,
      firstCurrent: "Lunch",
      firstNext: "E",
      firstDateTime: "11:20",
      secondCurrent: "E",
      secondNext: "Lunch",
      secondDateTime: "11:48",
      thirdCurrent: "E",
      thirdNext: "F",
      thirdDateTime: "11:48"),
  Schedule(
      hour: 10,
      minute: 47,
      firstCurrent: "Passing",
      firstNext: "Lunch",
      firstDateTime: "10:50",
      secondCurrent: "Passing",
      secondNext: "E",
      secondDateTime: "10:50",
      thirdCurrent: "Passing",
      thirdNext: "E",
      thirdDateTime: "10:50"),
  Schedule(
      hour: 9,
      minute: 49,
      firstCurrent: "C",
      firstNext: "Lunch",
      firstDateTime: "10:47",
      secondCurrent: "C",
      secondNext: "E",
      secondDateTime: "10:47",
      thirdCurrent: "C",
      thirdNext: "E",
      thirdDateTime: "10:47"),
  Schedule(
      hour: 9,
      minute: 46,
      firstCurrent: "Passing",
      firstNext: "C",
      firstDateTime: "9:49",
      secondCurrent: "Passing",
      secondNext: "C",
      secondDateTime: "9:49",
      thirdCurrent: "Passing",
      thirdNext: "C",
      thirdDateTime: "9:49"),
  Schedule(
      hour: 8,
      minute: 48,
      firstCurrent: "B",
      firstNext: "C",
      firstDateTime: "9:46",
      secondCurrent: "B",
      secondNext: "C",
      secondDateTime: "9:46",
      thirdCurrent: "B",
      thirdNext: "C",
      thirdDateTime: "9:46"),
  Schedule(
      hour: 8,
      minute: 45,
      firstCurrent: "Passing",
      firstNext: "B",
      firstDateTime: "8:48",
      secondCurrent: "Passing",
      secondNext: "B",
      secondDateTime: "8:48",
      thirdCurrent: "Passing",
      thirdNext: "B",
      thirdDateTime: "8:48"),
  Schedule(
      hour: 7,
      minute: 45,
      firstCurrent: "A",
      firstNext: "B",
      firstDateTime: "8:45",
      secondCurrent: "A",
      secondNext: "B",
      secondDateTime: "8:45",
      thirdCurrent: "A",
      thirdNext: "B",
      thirdDateTime: "8:45"),
  Schedule(
      hour: 7,
      minute: 43,
      firstCurrent: "2nd Bell",
      firstNext: "A",
      firstDateTime: "7:45",
      secondCurrent: "2nd Bell",
      secondNext: "A",
      secondDateTime: "7:45",
      thirdCurrent: "2nd Bell",
      thirdNext: "A",
      thirdDateTime: "7:45"),
  Schedule(
      hour: 7,
      minute: 40,
      firstCurrent: "Passing",
      firstNext: "A",
      firstDateTime: "7:45",
      secondCurrent: "Passing",
      secondNext: "A",
      secondDateTime: "7:45",
      thirdCurrent: "Passing",
      thirdNext: "A",
      thirdDateTime: "7:45"),
  Schedule(
      hour: 7,
      minute: 35,
      firstCurrent: "Opening",
      firstNext: "A",
      firstDateTime: "7:45",
      secondCurrent: "Opening",
      secondNext: "A",
      secondDateTime: "7:45",
      thirdCurrent: "Opening",
      thirdNext: "A",
      thirdDateTime: "7:45"),
  Schedule(
      hour: 6,
      minute: 45,
      firstCurrent: "Open",
      firstNext: "A",
      firstDateTime: "7:45",
      secondCurrent: "Open",
      secondNext: "A",
      secondDateTime: "7:45",
      thirdCurrent: "Open",
      thirdNext: "A",
      thirdDateTime: "7:45"),
];

List<Schedule> fridayList = [
  Schedule(
      hour: 13,
      minute: 26,
      firstCurrent: "H",
      firstNext: "Let Out",
      firstDateTime: "14:24",
      secondCurrent: "H",
      secondNext: "Let Out",
      secondDateTime: "14:24",
      thirdCurrent: "H",
      thirdNext: "Let Out",
      thirdDateTime: "14:24"),
  Schedule(
      hour: 13,
      minute: 22,
      firstCurrent: "Passing",
      firstNext: "H",
      firstDateTime: "13:26",
      secondCurrent: "Passing",
      secondNext: "H",
      secondDateTime: "13:26",
      thirdCurrent: "Passing",
      thirdNext: "H",
      thirdDateTime: "13:26"),
  Schedule(
      hour: 12,
      minute: 52,
      firstCurrent: "G",
      firstNext: "H",
      firstDateTime: "13:22",
      secondCurrent: "G",
      secondNext: "H",
      secondDateTime: "13:22",
      thirdCurrent: "Lunch",
      thirdNext: "H",
      thirdDateTime: "13:22"),
  Schedule(
      hour: 12,
      minute: 49,
      firstCurrent: "G",
      firstNext: "H",
      firstDateTime: "13:26",
      secondCurrent: "G",
      secondNext: "H",
      secondDateTime: "13:26",
      thirdCurrent: "Passing",
      thirdNext: "Lunch",
      thirdDateTime: "12:52"),
  Schedule(
      hour: 12,
      minute: 24,
      firstCurrent: "G",
      firstNext: "H",
      firstDateTime: "13:26",
      secondCurrent: "G",
      secondNext: "H",
      secondDateTime: "13:26",
      thirdCurrent: "G",
      thirdNext: "Lunch",
      thirdDateTime: "12:49"),
  Schedule(
      hour: 12,
      minute: 21,
      firstCurrent: "Passing",
      firstNext: "G",
      firstDateTime: "12:24",
      secondCurrent: "Passing",
      secondNext: "G",
      secondDateTime: "12:24",
      thirdCurrent: "G",
      thirdNext: "Lunch",
      thirdDateTime: "12:49"),
  Schedule(
      hour: 11,
      minute: 51,
      firstCurrent: "F",
      firstNext: "G",
      firstDateTime: "12:21",
      secondCurrent: "Lunch",
      secondNext: "G",
      secondDateTime: "12:21",
      thirdCurrent: "G",
      thirdNext: "Lunch",
      thirdDateTime: "12:49"),
  Schedule(
      hour: 11,
      minute: 48,
      firstCurrent: "F",
      firstNext: "G",
      firstDateTime: "12:21",
      secondCurrent: "Passing",
      secondNext: "Lunch",
      secondDateTime: "11:51",
      thirdCurrent: "Passing",
      thirdNext: "G",
      thirdDateTime: "11:51"),
  Schedule(
      hour: 11,
      minute: 23,
      firstCurrent: "F",
      firstNext: "G",
      firstDateTime: "12:21",
      secondCurrent: "F",
      secondNext: "Lunch",
      secondDateTime: "11:48",
      thirdCurrent: "F",
      thirdNext: "G",
      thirdDateTime: "11:48"),
  Schedule(
      hour: 11,
      minute: 20,
      firstCurrent: "Passing",
      firstNext: "F",
      firstDateTime: "11:23",
      secondCurrent: "F",
      secondNext: "Lunch",
      secondDateTime: "11:48",
      thirdCurrent: "F",
      thirdNext: "G",
      thirdDateTime: "11:48"),
  Schedule(
      hour: 10,
      minute: 50,
      firstCurrent: "Lunch",
      firstNext: "F",
      firstDateTime: "11:20",
      secondCurrent: "F",
      secondNext: "Lunch",
      secondDateTime: "11:48",
      thirdCurrent: "F",
      thirdNext: "G",
      thirdDateTime: "11:48"),
  Schedule(
      hour: 10,
      minute: 47,
      firstCurrent: "Passing",
      firstNext: "Lunch",
      firstDateTime: "10:50",
      secondCurrent: "Passing",
      secondNext: "F",
      secondDateTime: "10:50",
      thirdCurrent: "Passing",
      thirdNext: "F",
      thirdDateTime: "10:50"),
  Schedule(
      hour: 9,
      minute: 49,
      firstCurrent: "D",
      firstNext: "Lunch",
      firstDateTime: "10:47",
      secondCurrent: "D",
      secondNext: "F",
      secondDateTime: "10:47",
      thirdCurrent: "D",
      thirdNext: "F",
      thirdDateTime: "10:47"),
  Schedule(
      hour: 9,
      minute: 46,
      firstCurrent: "Passing",
      firstNext: "D",
      firstDateTime: "9:49",
      secondCurrent: "Passing",
      secondNext: "D",
      secondDateTime: "9:49",
      thirdCurrent: "Passing",
      thirdNext: "D",
      thirdDateTime: "9:49"),
  Schedule(
      hour: 8,
      minute: 48,
      firstCurrent: "C",
      firstNext: "D",
      firstDateTime: "9:46",
      secondCurrent: "C",
      secondNext: "D",
      secondDateTime: "9:46",
      thirdCurrent: "C",
      thirdNext: "D",
      thirdDateTime: "9:46"),
  Schedule(
      hour: 8,
      minute: 45,
      firstCurrent: "Passing",
      firstNext: "C",
      firstDateTime: "8:48",
      secondCurrent: "Passing",
      secondNext: "C",
      secondDateTime: "8:48",
      thirdCurrent: "Passing",
      thirdNext: "C",
      thirdDateTime: "8:48"),
  Schedule(
      hour: 7,
      minute: 45,
      firstCurrent: "B",
      firstNext: "C",
      firstDateTime: "8:45",
      secondCurrent: "B",
      secondNext: "C",
      secondDateTime: "8:45",
      thirdCurrent: "B",
      thirdNext: "C",
      thirdDateTime: "8:45"),
  Schedule(
      hour: 7,
      minute: 43,
      firstCurrent: "2nd Bell",
      firstNext: "B",
      firstDateTime: "7:45",
      secondCurrent: "2nd Bell",
      secondNext: "B",
      secondDateTime: "7:45",
      thirdCurrent: "2nd Bell",
      thirdNext: "B",
      thirdDateTime: "7:45"),
  Schedule(
      hour: 7,
      minute: 40,
      firstCurrent: "Passing",
      firstNext: "B",
      firstDateTime: "7:45",
      secondCurrent: "Passing",
      secondNext: "B",
      secondDateTime: "7:45",
      thirdCurrent: "Passing",
      thirdNext: "B",
      thirdDateTime: "7:45"),
  Schedule(
      hour: 7,
      minute: 35,
      firstCurrent: "Opening",
      firstNext: "B",
      firstDateTime: "7:45",
      secondCurrent: "Opening",
      secondNext: "B",
      secondDateTime: "7:45",
      thirdCurrent: "Opening",
      thirdNext: "B",
      thirdDateTime: "7:45"),
  Schedule(
      hour: 6,
      minute: 45,
      firstCurrent: "Open",
      firstNext: "B",
      firstDateTime: "7:45",
      secondCurrent: "Open",
      secondNext: "B",
      secondDateTime: "7:45",
      thirdCurrent: "Open",
      thirdNext: "B",
      thirdDateTime: "7:45"),
];

List<Schedule> earlyDismissalList = [];

List<Schedule> lateArrivalList = [];