import 'class_schedule.dart';
import 'map_schedule_entries.dart';

List<Schedule> mondayList = [
  Schedule(
      hour: 13,
      minute: 41,
      first: scheduleEntries["H-1424-Fin"]!,
      second: scheduleEntries["H-1424-Fin"]!,
      third: scheduleEntries["H-1424-Fin"]!),
  Schedule(
      hour: 13,
      minute: 38,
      first: scheduleEntries["Pass-1341-H"]!,
      second: scheduleEntries["Pass-1341-H"]!,
      third: scheduleEntries["Pass-1341-H"]!),
  Schedule(
      hour: 12,
      minute: 56,
      first: scheduleEntries["G-1338-H"]!,
      second: scheduleEntries["G-1338-H"]!,
      third: scheduleEntries["G-1338-H"]!),
  Schedule(
      hour: 12,
      minute: 53,
      first: scheduleEntries["Pass-1256-G"]!,
      second: scheduleEntries["Pass-1256-G"]!,
      third: scheduleEntries["Pass-1256-G"]!),
  Schedule(
      hour: 12,
      minute: 23,
      first: scheduleEntries["F-1253-G"]!,
      second: scheduleEntries["F-1253-G"]!,
      third: scheduleEntries["L-1253-G"]!),
  Schedule(
      hour: 12,
      minute: 20,
      first: scheduleEntries["F-1253-G"]!,
      second: scheduleEntries["F-1253-G"]!,
      third: scheduleEntries["Pass-1223-L"]!),
  Schedule(
      hour: 12,
      minute: 10,
      first: scheduleEntries["F-1253-G"]!,
      second: scheduleEntries["F-1253-G"]!,
      third: scheduleEntries["F-1220-L"]!),
  Schedule(
      hour: 12,
      minute: 7,
      first: scheduleEntries["Pass-1210-F"]!,
      second: scheduleEntries["Pass-1210-F"]!,
      third: scheduleEntries["F-1220-L"]!),
  Schedule(
      hour: 11,
      minute: 37,
      first: scheduleEntries["E-F-1207"]!,
      second: scheduleEntries["L-1207-F"]!,
      third: scheduleEntries["F-1220-L"]!),
  Schedule(
      hour: 11,
      minute: 34,
      first: scheduleEntries["E-F-1207"]!,
      second: scheduleEntries["Pass-1137-L"]!,
      third: scheduleEntries["Pass-1137-F"]!),
  Schedule(
      hour: 11,
      minute: 24,
      first: scheduleEntries["E-F-1207"]!,
      second: scheduleEntries["E-1134-L"]!,
      third: scheduleEntries["E-1134-F"]!),
  Schedule(
      hour: 11,
      minute: 21,
      first: scheduleEntries["Pass-1124-E"]!,
      second: scheduleEntries["E-1134-L"]!,
      third: scheduleEntries["E-1134-F"]!),
  Schedule(
      hour: 10,
      minute: 51,
      first: scheduleEntries["L-1121-E"]!,
      second: scheduleEntries["E-1134-L"]!,
      third: scheduleEntries["E-1134-F"]!),
  Schedule(
      hour: 10,
      minute: 48,
      first: scheduleEntries["Pass-1051-L"]!,
      second: scheduleEntries["Pass-1051-E"]!,
      third: scheduleEntries["Pass-1051-E"]!),
  Schedule(
      hour: 10,
      minute: 5,
      first: scheduleEntries["D-1048-L"]!,
      second: scheduleEntries["D-1048-E"]!,
      third: scheduleEntries["D-1048-E"]!),
  Schedule(
      hour: 10,
      minute: 2,
      first: scheduleEntries["Pass-1005-D"]!,
      second: scheduleEntries["Pass-1005-D"]!,
      third: scheduleEntries["Pass-1005-D"]!),
  Schedule(
      hour: 9,
      minute: 19,
      first: scheduleEntries["C-1002-D"]!,
      second: scheduleEntries["C-1002-D"]!,
      third: scheduleEntries["C-1002-D"]!),
  Schedule(
      hour: 9,
      minute: 16,
      first: scheduleEntries["Pass-919-C"]!,
      second: scheduleEntries["Pass-919-C"]!,
      third: scheduleEntries["Pass-919-C"]!),
  Schedule(
      hour: 8,
      minute: 33,
      first: scheduleEntries["B-916-C"]!,
      second: scheduleEntries["B-916-C"]!,
      third: scheduleEntries["B-916-C"]!),
  Schedule(
      hour: 8,
      minute: 30,
      first: scheduleEntries["Pass-833-B"]!,
      second: scheduleEntries["Pass-833-B"]!,
      third: scheduleEntries["Pass-833-B"]!),
  Schedule(
      hour: 7,
      minute: 45,
      first: scheduleEntries["A-830-B"]!,
      second: scheduleEntries["A-830-B"]!,
      third: scheduleEntries["A-830-B"]!),
  Schedule(
      hour: 7,
      minute: 43,
      first: scheduleEntries["Second-745-A"]!,
      second: scheduleEntries["Second-745-A"]!,
      third: scheduleEntries["Second-745-A"]!),
  Schedule(
      hour: 7,
      minute: 40,
      first: scheduleEntries["Pass-745-A"]!,
      second: scheduleEntries["Pass-745-A"]!,
      third: scheduleEntries["Pass-745-A"]!),
  Schedule(
      hour: 7,
      minute: 35,
      first: scheduleEntries["First-745-A"]!,
      second: scheduleEntries["First-745-A"]!,
      third: scheduleEntries["First-745-A"]!),
  Schedule(
      hour: 6,
      minute: 45,
      first: scheduleEntries["Open-745-A"]!,
      second: scheduleEntries["Open-745-A"]!,
      third: scheduleEntries["Open-745-A"]!),
];

List<Schedule> tuesdayList = [
  Schedule(
      hour: 13,
      minute: 26,
      first: scheduleEntries["H-1424-Fin"]!,
      second: scheduleEntries["H-1424-Fin"]!,
      third: scheduleEntries["H-1424-Fin"]!),
  Schedule(
      hour: 13,
      minute: 22,
      first: scheduleEntries["Pass-1326-H"]!,
      second: scheduleEntries["Pass-1326-H"]!,
      third: scheduleEntries["Pass-1326-H"]!),
  Schedule(
      hour: 12,
      minute: 52,
      first: scheduleEntries["F-1322-H"]!,
      second: scheduleEntries["F-1322-H"]!,
      third: scheduleEntries["L-1322-H"]!),
  Schedule(
      hour: 12,
      minute: 49,
      first: scheduleEntries["F-1322-H"]!,
      second: scheduleEntries["F-1322-H"]!,
      third: scheduleEntries["Pass-1252-L"]!),
  Schedule(
      hour: 12,
      minute: 24,
      first: scheduleEntries["F-1322-H"]!,
      second: scheduleEntries["F-1322-H"]!,
      third: scheduleEntries["F-1249-L"]!),
  Schedule(
      hour: 12,
      minute: 21,
      first: scheduleEntries["Pass-1224-F"]!,
      second: scheduleEntries["Pass-1224-F"]!,
      third: scheduleEntries["F-1249-L"]!),
  Schedule(
      hour: 11,
      minute: 51,
      first: scheduleEntries["E-1221-F"]!,
      second: scheduleEntries["L-1221-F"]!,
      third: scheduleEntries["F-1249-L"]!),
  Schedule(
      hour: 11,
      minute: 48,
      first: scheduleEntries["E-1221-F"]!,
      second: scheduleEntries["Pass-1151-L"]!,
      third: scheduleEntries["Pass-1151-F"]!),
  Schedule(
      hour: 11,
      minute: 23,
      first: scheduleEntries["E-1221-F"]!,
      second: scheduleEntries["E-1148-L"]!,
      third: scheduleEntries["E-1148-F"]!),
  Schedule(
      hour: 11,
      minute: 20,
      first: scheduleEntries["Pass-1123-E"]!,
      second: scheduleEntries["E-1148-L"]!,
      third: scheduleEntries["E-1148-F"]!),
  Schedule(
      hour: 10,
      minute: 50,
      first: scheduleEntries["L-1120-E"]!,
      second: scheduleEntries["E-1148-L"]!,
      third: scheduleEntries["E-1148-F"]!),
  Schedule(
      hour: 10,
      minute: 47,
      first: scheduleEntries["Pass-1050-L"]!,
      second: scheduleEntries["Pass-1050-E"]!,
      third: scheduleEntries["Pass-1050-E"]!),
  Schedule(
      hour: 9,
      minute: 49,
      first: scheduleEntries["D-1047-L"]!,
      second: scheduleEntries["D-1047-E"]!,
      third: scheduleEntries["D-1047-E"]!),
  Schedule(
      hour: 9,
      minute: 46,
      first: scheduleEntries["Pass-949-D"]!,
      second: scheduleEntries["Pass-949-D"]!,
      third: scheduleEntries["Pass-949-D"]!),
  Schedule(
      hour: 8,
      minute: 48,
      first: scheduleEntries["B-946-D"]!,
      second: scheduleEntries["B-946-D"]!,
      third: scheduleEntries["B-946-D"]!),
  Schedule(
      hour: 8,
      minute: 45,
      first: scheduleEntries["Pass-848-B"]!,
      second: scheduleEntries["Pass-848-B"]!,
      third: scheduleEntries["Pass-848-B"]!),
  Schedule(
      hour: 7,
      minute: 45,
      first: scheduleEntries["A-845-B"]!,
      second: scheduleEntries["A-845-B"]!,
      third: scheduleEntries["A-845-B"]!),
  Schedule(
      hour: 7,
      minute: 43,
      first: scheduleEntries["Second-745-A"]!,
      second: scheduleEntries["Second-745-A"]!,
      third: scheduleEntries["Second-745-A"]!),
  Schedule(
      hour: 7,
      minute: 40,
      first: scheduleEntries["Pass-745-A"]!,
      second: scheduleEntries["Pass-745-A"]!,
      third: scheduleEntries["Pass-745-A"]!),
  Schedule(
      hour: 7,
      minute: 35,
      first: scheduleEntries["First-745-A"]!,
      second: scheduleEntries["First-745-A"]!,
      third: scheduleEntries["First-745-A"]!),
  Schedule(
      hour: 6,
      minute: 45,
      first: scheduleEntries["Open-745-A"]!,
      second: scheduleEntries["Open-745-A"]!,
      third: scheduleEntries["Open-745-A"]!),
];

List<Schedule> wednesdayList = [
  Schedule(
      hour: 13,
      minute: 26,
      first: scheduleEntries["H-1424-Fin"]!,
      second: scheduleEntries["H-1424-Fin"]!,
      third: scheduleEntries["H-1424-Fin"]!),
  Schedule(
      hour: 13,
      minute: 22,
      first: scheduleEntries["Pass-1326-H"]!,
      second: scheduleEntries["Pass-1326-H"]!,
      third: scheduleEntries["Pass-1326-H"]!),
  Schedule(
      hour: 12,
      minute: 52,
      first: scheduleEntries["G-1322-H"]!,
      second: scheduleEntries["G-1322-H"]!,
      third: scheduleEntries["L-1322-H"]!),
  Schedule(
      hour: 12,
      minute: 49,
      first: scheduleEntries["G-1322-H"]!,
      second: scheduleEntries["G-1322-H"]!,
      third: scheduleEntries["Pass-1252-L"]!),
  Schedule(
      hour: 12,
      minute: 24,
      first: scheduleEntries["G-1322-H"]!,
      second: scheduleEntries["G-1322-H"]!,
      third: scheduleEntries["G-1249-L"]!),
  Schedule(
      hour: 12,
      minute: 21,
      first: scheduleEntries["Pass-1224-G"]!,
      second: scheduleEntries["Pass-1224-G"]!,
      third: scheduleEntries["G-1249-L"]!),
  Schedule(
      hour: 11,
      minute: 51,
      first: scheduleEntries["E-1221-G"]!,
      second: scheduleEntries["L-1221-G"]!,
      third: scheduleEntries["G-1249-L"]!),
  Schedule(
      hour: 11,
      minute: 48,
      first: scheduleEntries["E-1221-G"]!,
      second: scheduleEntries["Pass-1151-L"]!,
      third: scheduleEntries["Pass-1151-G"]!),
  Schedule(
      hour: 11,
      minute: 23,
      first: scheduleEntries["E-1221-G"]!,
      second: scheduleEntries["E-1148-L"]!,
      third: scheduleEntries["E-1148-G"]!),
  Schedule(
      hour: 11,
      minute: 20,
      first: scheduleEntries["Pass-1123-E"]!,
      second: scheduleEntries["E-1148-L"]!,
      third: scheduleEntries["E-1148-G"]!),
  Schedule(
      hour: 10,
      minute: 50,
      first: scheduleEntries["L-1120-E"]!,
      second: scheduleEntries["E-1148-L"]!,
      third: scheduleEntries["E-1148-G"]!),
  Schedule(
      hour: 10,
      minute: 47,
      first: scheduleEntries["Pass-1050-L"]!,
      second: scheduleEntries["Pass-1050-E"]!,
      third: scheduleEntries["Pass-1050-E"]!),
  Schedule(
      hour: 9,
      minute: 49,
      first: scheduleEntries["D-1047-L"]!,
      second: scheduleEntries["D-1047-E"]!,
      third: scheduleEntries["D-1047-E"]!),
  Schedule(
      hour: 9,
      minute: 46,
      first: scheduleEntries["Pass-949-D"]!,
      second: scheduleEntries["Pass-949-D"]!,
      third: scheduleEntries["Pass-949-D"]!),
  Schedule(
      hour: 8,
      minute: 48,
      first: scheduleEntries["C-946-D"]!,
      second: scheduleEntries["C-946-D"]!,
      third: scheduleEntries["C-946-D"]!),
  Schedule(
      hour: 8,
      minute: 45,
      first: scheduleEntries["Pass-848-C"]!,
      second: scheduleEntries["Pass-848-C"]!,
      third: scheduleEntries["Pass-848-C"]!),
  Schedule(
      hour: 7,
      minute: 45,
      first: scheduleEntries["A-845-C"]!,
      second: scheduleEntries["A-845-C"]!,
      third: scheduleEntries["A-845-C"]!),
  Schedule(
      hour: 7,
      minute: 43,
      first: scheduleEntries["Second-745-A"]!,
      second: scheduleEntries["Second-745-A"]!,
      third: scheduleEntries["Second-745-A"]!),
  Schedule(
      hour: 7,
      minute: 40,
      first: scheduleEntries["Pass-745-A"]!,
      second: scheduleEntries["Pass-745-A"]!,
      third: scheduleEntries["Pass-745-A"]!),
  Schedule(
      hour: 7,
      minute: 35,
      first: scheduleEntries["First-745-A"]!,
      second: scheduleEntries["First-745-A"]!,
      third: scheduleEntries["First-745-A"]!),
  Schedule(
      hour: 6,
      minute: 45,
      first: scheduleEntries["Open-745-A"]!,
      second: scheduleEntries["Open-745-A"]!,
      third: scheduleEntries["Open-745-A"]!),
];

List<Schedule> thursdayList = [
  Schedule(
      hour: 13,
      minute: 26,
      first: scheduleEntries["G-1424-Fin"]!,
      second: scheduleEntries["G-1424-Fin"]!,
      third: scheduleEntries["G-1424-Fin"]!),
  Schedule(
      hour: 13,
      minute: 22,
      first: scheduleEntries["Pass-1326-G"]!,
      second: scheduleEntries["Pass-1326-G"]!,
      third: scheduleEntries["Pass-1326-G"]!),
  Schedule(
      hour: 12,
      minute: 52,
      first: scheduleEntries["F-1322-G"]!,
      second: scheduleEntries["F-1322-G"]!,
      third: scheduleEntries["L-1322-G"]!),
  Schedule(
      hour: 12,
      minute: 49,
      first: scheduleEntries["F-1322-G"]!,
      second: scheduleEntries["F-1322-G"]!,
      third: scheduleEntries["Pass-1252-L"]!),
  Schedule(
      hour: 12,
      minute: 24,
      first: scheduleEntries["F-1322-G"]!,
      second: scheduleEntries["F-1322-G"]!,
      third: scheduleEntries["F-1249-L"]!),
  Schedule(
      hour: 12,
      minute: 21,
      first: scheduleEntries["Pass-1224-F"]!,
      second: scheduleEntries["Pass-1224-F"]!,
      third: scheduleEntries["F-1249-L"]!),
  Schedule(
      hour: 11,
      minute: 51,
      first: scheduleEntries["E-F-1221"]!,
      second: scheduleEntries["L-1221-F"]!,
      third: scheduleEntries["F-1249-L"]!),
  Schedule(
      hour: 11,
      minute: 48,
      first: scheduleEntries["E-F-1221"]!,
      second: scheduleEntries["Pass-1151-L"]!,
      third: scheduleEntries["Pass-1151-F"]!),
  Schedule(
      hour: 11,
      minute: 23,
      first: scheduleEntries["E-1221-F"]!,
      second: scheduleEntries["E-1148-L"]!,
      third: scheduleEntries["E-1148-F"]!),
  Schedule(
      hour: 11,
      minute: 20,
      first: scheduleEntries["Pass-1123-E"]!,
      second: scheduleEntries["E-1148-L"]!,
      third: scheduleEntries["E-1148-F"]!),
  Schedule(
      hour: 10,
      minute: 50,
      first: scheduleEntries["L-1120-E"]!,
      second: scheduleEntries["E-1148-L"]!,
      third: scheduleEntries["E-1148-F"]!),
  Schedule(
      hour: 10,
      minute: 47,
      first: scheduleEntries["Pass-1050-L"]!,
      second: scheduleEntries["Pass-1050-E"]!,
      third: scheduleEntries["Pass-1050-E"]!),
  Schedule(
      hour: 9,
      minute: 49,
      first: scheduleEntries["C-1047-L"]!,
      second: scheduleEntries["C-1047-E"]!,
      third: scheduleEntries["C-1047-E"]!),
  Schedule(
      hour: 9,
      minute: 46,
      first: scheduleEntries["Pass-949-C"]!,
      second: scheduleEntries["Pass-949-C"]!,
      third: scheduleEntries["Pass-949-C"]!),
  Schedule(
      hour: 8,
      minute: 48,
      first: scheduleEntries["B-946-C"]!,
      second: scheduleEntries["B-946-C"]!,
      third: scheduleEntries["B-946-C"]!),
  Schedule(
      hour: 8,
      minute: 45,
      first: scheduleEntries["Pass-848-B"]!,
      second: scheduleEntries["Pass-848-B"]!,
      third: scheduleEntries["Pass-848-B"]!),
  Schedule(
      hour: 7,
      minute: 45,
      first: scheduleEntries["A-845-B"]!,
      second: scheduleEntries["A-845-B"]!,
      third: scheduleEntries["A-845-B"]!),
  Schedule(
      hour: 7,
      minute: 43,
      first: scheduleEntries["Second-745-A"]!,
      second: scheduleEntries["Second-745-A"]!,
      third: scheduleEntries["Second-745-A"]!),
  Schedule(
      hour: 7,
      minute: 40,
      first: scheduleEntries["Pass-745-A"]!,
      second: scheduleEntries["Pass-745-A"]!,
      third: scheduleEntries["Pass-745-A"]!),
  Schedule(
      hour: 7,
      minute: 35,
      first: scheduleEntries["First-745-A"]!,
      second: scheduleEntries["First-745-A"]!,
      third: scheduleEntries["First-745-A"]!),
  Schedule(
      hour: 6,
      minute: 45,
      first: scheduleEntries["Open-745-A"]!,
      second: scheduleEntries["Open-745-A"]!,
      third: scheduleEntries["Open-745-A"]!),
];

List<Schedule> fridayList = [
  Schedule(
      hour: 13,
      minute: 26,
      first: scheduleEntries["H-1424-Fin"]!,
      second: scheduleEntries["H-1424-Fin"]!,
      third: scheduleEntries["H-1424-Fin"]!),
  Schedule(
      hour: 13,
      minute: 22,
      first: scheduleEntries["Pass-1326-H"]!,
      second: scheduleEntries["Pass-1326-H"]!,
      third: scheduleEntries["Pass-1326-H"]!),
  Schedule(
      hour: 12,
      minute: 52,
      first: scheduleEntries["G-1322-H"]!,
      second: scheduleEntries["G-1322-H"]!,
      third: scheduleEntries["L-1322-H"]!),
  Schedule(
      hour: 12,
      minute: 49,
      first: scheduleEntries["G-1322-H"]!,
      second: scheduleEntries["G-1322-H"]!,
      third: scheduleEntries["Pass-1252-L"]!),
  Schedule(
      hour: 12,
      minute: 24,
      first: scheduleEntries["G-1322-H"]!,
      second: scheduleEntries["G-1322-H"]!,
      third: scheduleEntries["G-1249-L"]!),
  Schedule(
      hour: 12,
      minute: 21,
      first: scheduleEntries["Pass-1224-G"]!,
      second: scheduleEntries["Pass-1224-G"]!,
      third: scheduleEntries["G-1249-L"]!),
  Schedule(
      hour: 11,
      minute: 51,
      first: scheduleEntries["F-1221-G"]!,
      second: scheduleEntries["L-1221-G"]!,
      third: scheduleEntries["G-1249-L"]!),
  Schedule(
      hour: 11,
      minute: 48,
      first: scheduleEntries["F-1221-G"]!,
      second: scheduleEntries["Pass-1151-L"]!,
      third: scheduleEntries["Pass-1151-G"]!),
  Schedule(
      hour: 11,
      minute: 23,
      first: scheduleEntries["F-1221-G"]!,
      second: scheduleEntries["F-1148-L"]!,
      third: scheduleEntries["F-1148-G"]!),
  Schedule(
      hour: 11,
      minute: 20,
      first: scheduleEntries["Pass-1123-F"]!,
      second: scheduleEntries["F-1148-L"]!,
      third: scheduleEntries["E-1148-G"]!),
  Schedule(
      hour: 10,
      minute: 50,
      first: scheduleEntries["L-1120-F"]!,
      second: scheduleEntries["F-1148-L"]!,
      third: scheduleEntries["F-1148-G"]!),
  Schedule(
      hour: 10,
      minute: 47,
      first: scheduleEntries["Pass-1050-L"]!,
      second: scheduleEntries["Pass-1050-F"]!,
      third: scheduleEntries["Pass-1050-F"]!),
  Schedule(
      hour: 9,
      minute: 49,
      first: scheduleEntries["D-1047-L"]!,
      second: scheduleEntries["D-1047-F"]!,
      third: scheduleEntries["D-1047-F"]!),
  Schedule(
      hour: 9,
      minute: 46,
      first: scheduleEntries["Pass-949-D"]!,
      second: scheduleEntries["Pass-949-D"]!,
      third: scheduleEntries["Pass-949-D"]!),
  Schedule(
      hour: 8,
      minute: 48,
      first: scheduleEntries["C-946-D"]!,
      second: scheduleEntries["C-946-D"]!,
      third: scheduleEntries["C-946-D"]!),
  Schedule(
      hour: 8,
      minute: 45,
      first: scheduleEntries["Pass-848-C"]!,
      second: scheduleEntries["Pass-848-C"]!,
      third: scheduleEntries["Pass-848-C"]!),
  Schedule(
      hour: 7,
      minute: 45,
      first: scheduleEntries["B-845-C"]!,
      second: scheduleEntries["B-845-C"]!,
      third: scheduleEntries["B-845-C"]!),
  Schedule(
      hour: 7,
      minute: 43,
      first: scheduleEntries["Second-745-B"]!,
      second: scheduleEntries["Second-745-B"]!,
      third: scheduleEntries["Second-745-B"]!),
  Schedule(
      hour: 7,
      minute: 40,
      first: scheduleEntries["Pass-745-B"]!,
      second: scheduleEntries["Pass-745-B"]!,
      third: scheduleEntries["Pass-745-B"]!),
  Schedule(
      hour: 7,
      minute: 35,
      first: scheduleEntries["First-745-B"]!,
      second: scheduleEntries["First-745-B"]!,
      third: scheduleEntries["First-745-B"]!),
  Schedule(
      hour: 6,
      minute: 45,
      first: scheduleEntries["Open-745-B"]!,
      second: scheduleEntries["Open-745-B"]!,
      third: scheduleEntries["Open-745-B"]!),
];

List<Schedule> earlyDismissal11_1List = [
  Schedule(
      hour: 10,
      minute: 24,
      first: scheduleEntries["F-1115-Fin"]!,
      second: scheduleEntries["F-1115-Fin"]!,
      third: scheduleEntries["F-1115-Fin"]!),
  Schedule(
      hour: 10,
      minute: 21,
      first: scheduleEntries["Pass-1024-F"]!,
      second: scheduleEntries["Pass-1024-F"]!,
      third: scheduleEntries["Pass-1024-F"]!),
  Schedule(
      hour: 9,
      minute: 31,
      first: scheduleEntries["D-1021-F"]!,
      second: scheduleEntries["D-1021-F"]!,
      third: scheduleEntries["D-1021-F"]!),
  Schedule(
      hour: 9,
      minute: 28,
      first: scheduleEntries["Pass-931-D"]!,
      second: scheduleEntries["Pass-931-D"]!,
      third: scheduleEntries["Pass-931-D"]!),
  Schedule(
      hour: 8,
      minute: 38,
      first: scheduleEntries["C-928-D"]!,
      second: scheduleEntries["C-928-D"]!,
      third: scheduleEntries["C-928-D"]!),
  Schedule(
      hour: 8,
      minute: 35,
      first: scheduleEntries["Pass-838-C"]!,
      second: scheduleEntries["Pass-838-C"]!,
      third: scheduleEntries["Pass-838-C"]!),
  Schedule(
      hour: 7,
      minute: 45,
      first: scheduleEntries["B-835-C"]!,
      second: scheduleEntries["B-835-C"]!,
      third: scheduleEntries["B-835-C"]!),
  Schedule(
      hour: 7,
      minute: 43,
      first: scheduleEntries["Second-745-B"]!,
      second: scheduleEntries["Second-745-B"]!,
      third: scheduleEntries["Second-745-B"]!),
  Schedule(
      hour: 7,
      minute: 40,
      first: scheduleEntries["Pass-745-B"]!,
      second: scheduleEntries["Pass-745-B"]!,
      third: scheduleEntries["Pass-745-B"]!),
  Schedule(
      hour: 7,
      minute: 35,
      first: scheduleEntries["First-745-B"]!,
      second: scheduleEntries["First-745-B"]!,
      third: scheduleEntries["First-745-B"]!),
  Schedule(
      hour: 6,
      minute: 45,
      first: scheduleEntries["Open-745-B"]!,
      second: scheduleEntries["Open-745-B"]!,
      third: scheduleEntries["Open-745-B"]!),
];

List<Schedule> earlyDismissal4_18List = [
  Schedule(
      hour: 10,
      minute: 51,
      first: scheduleEntries["H-1115-Fin"]!,
      second: scheduleEntries["H-1115-Fin"]!,
      third: scheduleEntries["H-1115-Fin"]!),
  Schedule(
      hour: 10,
      minute: 48,
      first: scheduleEntries["Pass-1051-H"]!,
      second: scheduleEntries["Pass-1051-H"]!,
      third: scheduleEntries["Pass-1051-H"]!),
  Schedule(
      hour: 10,
      minute: 25,
      first: scheduleEntries["G-1048-H"]!,
      second: scheduleEntries["G-1048-H"]!,
      third: scheduleEntries["G-1048-H"]!),
  Schedule(
      hour: 10,
      minute: 22,
      first: scheduleEntries["Pass-1025-G"]!,
      second: scheduleEntries["Pass-1025-G"]!,
      third: scheduleEntries["Pass-1025-G"]!),
  Schedule(
      hour: 9,
      minute: 58,
      first: scheduleEntries["F-1022-G"]!,
      second: scheduleEntries["F-1022-G"]!,
      third: scheduleEntries["F-1022-G"]!),
  Schedule(
      hour: 9,
      minute: 55,
      first: scheduleEntries["Pass-958-F"]!,
      second: scheduleEntries["Pass-958-F"]!,
      third: scheduleEntries["Pass-958-F"]!),
  Schedule(
      hour: 9,
      minute: 32,
      first: scheduleEntries["E-955-F"]!,
      second: scheduleEntries["E-955-F"]!,
      third: scheduleEntries["E-955-F"]!),
  Schedule(
      hour: 9,
      minute: 29,
      first: scheduleEntries["Pass-932-E"]!,
      second: scheduleEntries["Pass-932-E"]!,
      third: scheduleEntries["Pass-932-E"]!),
  Schedule(
      hour: 9,
      minute: 5,
      first: scheduleEntries["D-929-E"]!,
      second: scheduleEntries["D-929-E"]!,
      third: scheduleEntries["D-929-E"]!),
  Schedule(
      hour: 9,
      minute: 2,
      first: scheduleEntries["Pass-905-D"]!,
      second: scheduleEntries["Pass-905-D"]!,
      third: scheduleEntries["Pass-905-D"]!),
  Schedule(
      hour: 8,
      minute: 39,
      first: scheduleEntries["C-902-D"]!,
      second: scheduleEntries["C-902-D"]!,
      third: scheduleEntries["C-902-D"]!),
  Schedule(
      hour: 8,
      minute: 36,
      first: scheduleEntries["Pass-839-C"]!,
      second: scheduleEntries["Pass-839-C"]!,
      third: scheduleEntries["Pass-839-C"]!),
  Schedule(
      hour: 8,
      minute: 12,
      first: scheduleEntries["B-836-C"]!,
      second: scheduleEntries["B-836-C"]!,
      third: scheduleEntries["B-836-C"]!),
  Schedule(
      hour: 8,
      minute: 9,
      first: scheduleEntries["Pass-812-B"]!,
      second: scheduleEntries["Pass-812-B"]!,
      third: scheduleEntries["Pass-812-B"]!),
  Schedule(
      hour: 7,
      minute: 45,
      first: scheduleEntries["A-809-B"]!,
      second: scheduleEntries["A-809-B"]!,
      third: scheduleEntries["A-809-B"]!),
  Schedule(
      hour: 7,
      minute: 43,
      first: scheduleEntries["Second-745-A"]!,
      second: scheduleEntries["Second-745-B"]!,
      third: scheduleEntries["Second-745-B"]!),
  Schedule(
      hour: 7,
      minute: 40,
      first: scheduleEntries["Pass-745-A"]!,
      second: scheduleEntries["Pass-745-B"]!,
      third: scheduleEntries["Pass-745-B"]!),
  Schedule(
      hour: 7,
      minute: 35,
      first: scheduleEntries["First-745-A"]!,
      second: scheduleEntries["First-745-B"]!,
      third: scheduleEntries["First-745-B"]!),
  Schedule(
      hour: 6,
      minute: 45,
      first: scheduleEntries["Open-745-A"]!,
      second: scheduleEntries["Open-745-B"]!,
      third: scheduleEntries["Open-745-B"]!),
];

List<Schedule> lateArrivalList = [
  Schedule(
      hour: 13,
      minute: 41,
      first: scheduleEntries["H-1424-Fin"]!,
      second: scheduleEntries["H-1424-Fin"]!,
      third: scheduleEntries["H-1424-Fin"]!),
  Schedule(
      hour: 13,
      minute: 38,
      first: scheduleEntries["Pass-1341-H"]!,
      second: scheduleEntries["Pass-1341-H"]!,
      third: scheduleEntries["Pass-1341-H"]!),
  Schedule(
      hour: 12,
      minute: 56,
      first: scheduleEntries["G-1338-H"]!,
      second: scheduleEntries["G-1338-H"]!,
      third: scheduleEntries["G-1338-H"]!),
  Schedule(
      hour: 12,
      minute: 53,
      first: scheduleEntries["Pass-1256-G"]!,
      second: scheduleEntries["Pass-1256-G"]!,
      third: scheduleEntries["Pass-1256-G"]!),
  Schedule(
      hour: 12,
      minute: 23,
      first: scheduleEntries["F-1253-G"]!,
      second: scheduleEntries["F-1253-G"]!,
      third: scheduleEntries["L-1253-G"]!),
  Schedule(
      hour: 12,
      minute: 20,
      first: scheduleEntries["F-1253-G"]!,
      second: scheduleEntries["F-1253-G"]!,
      third: scheduleEntries["Pass-1223-L"]!),
  Schedule(
      hour: 12,
      minute: 10,
      first: scheduleEntries["F-1253-G"]!,
      second: scheduleEntries["F-1253-G"]!,
      third: scheduleEntries["F-1220-L"]!),
  Schedule(
      hour: 12,
      minute: 7,
      first: scheduleEntries["Pass-1210-F"]!,
      second: scheduleEntries["Pass-1210-F"]!,
      third: scheduleEntries["F-1220-L"]!),
  Schedule(
      hour: 11,
      minute: 37,
      first: scheduleEntries["E-1207-F"]!,
      second: scheduleEntries["L-1207-F"]!,
      third: scheduleEntries["F-1220-L"]!),
  Schedule(
      hour: 11,
      minute: 34,
      first: scheduleEntries["E-1207-F"]!,
      second: scheduleEntries["Pass-1137-L"]!,
      third: scheduleEntries["Pass-1137-F"]!),
  Schedule(
      hour: 11,
      minute: 24,
      first: scheduleEntries["E-1207-F"]!,
      second: scheduleEntries["E-1134-L"]!,
      third: scheduleEntries["E-1134-F"]!),
  Schedule(
      hour: 11,
      minute: 21,
      first: scheduleEntries["Pass-1124-E"]!,
      second: scheduleEntries["E-1134-L"]!,
      third: scheduleEntries["E-1134-F"]!),
  Schedule(
      hour: 10,
      minute: 51,
      first: scheduleEntries["L-1121-E"]!,
      second: scheduleEntries["E-1134-L"]!,
      third: scheduleEntries["E-1134-F"]!),
  Schedule(
      hour: 10,
      minute: 48,
      first: scheduleEntries["Pass-1051-L"]!,
      second: scheduleEntries["Pass-1051-E"]!,
      third: scheduleEntries["Pass-1051-E"]!),
  Schedule(
      hour: 10,
      minute: 0,
      first: scheduleEntries["D-1048-L"]!,
      second: scheduleEntries["D-1048-E"]!,
      third: scheduleEntries["D-1048-E"]!),
  Schedule(
      hour: 9,
      minute: 58,
      first: scheduleEntries["Second-1000-D"]!,
      second: scheduleEntries["Second-1000-D"]!,
      third: scheduleEntries["Second-1000-D"]!),
  Schedule(
      hour: 9,
      minute: 55,
      first: scheduleEntries["Pass-1000-D"]!,
      second: scheduleEntries["Pass-1000-D"]!,
      third: scheduleEntries["Pass-1000-D"]!),
  Schedule(
      hour: 9,
      minute: 50,
      first: scheduleEntries["First-1000-D"]!,
      second: scheduleEntries["First-1000-D"]!,
      third: scheduleEntries["First-1000-D"]!),
  Schedule(
      hour: 9,
      minute: 0,
      first: scheduleEntries["Open-1000-D"]!,
      second: scheduleEntries["Open-1000-D"]!,
      third: scheduleEntries["Open-1000-D"]!),
];
